create table if not exists public.search_term_account_settings (
  "accountId" text primary key,
  "automationEnabled" boolean not null default false,
  cadence text not null default 'off' check (cadence in ('off', 'weekly', 'biweekly', 'monthly')),
  "nextRunAt" timestamptz,
  "updatedAt" timestamptz not null
);

create table if not exists public.search_term_runs (
  id text primary key,
  "accountId" text not null,
  "companyName" text not null,
  status text not null,
  "startedAt" timestamptz not null,
  "completedAt" timestamptz,
  "startDate" date not null,
  "endDate" date not null,
  "totalReviewed" integer not null default 0,
  error text
);
create index if not exists search_term_runs_account_started_idx
  on public.search_term_runs ("accountId", "startedAt" desc);

create table if not exists public.search_term_records (
  id text primary key,
  "runId" text not null,
  "accountId" text not null,
  payload jsonb not null default '{}'::jsonb
);
create index if not exists search_term_records_account_idx on public.search_term_records ("accountId");

-- The REST repository sends flattened records. Keep payload-compatible columns generated by
-- applying the project migration helper before production; memory mode remains the safe local default.
