type Command="retrieve"|"next"|"all"|"cancel";
type QueueMessage={command:Command;jobId:string;accountId:string;startDate:string;endDate:string};
type Env={ACCOUNT_DIRECTORY:D1Database;PLACEMENT_IMPORTS:R2Bucket;PLACEMENT_QUEUE:Queue<QueueMessage>;WORKER_API_SECRET:string;SUPABASE_URL:string;SUPABASE_SECRET_KEY:string;GOOGLE_ADS_DEVELOPER_TOKEN:string;GOOGLE_ADS_REFRESH_TOKEN:string;GOOGLE_ADS_CLIENT_ID:string;GOOGLE_ADS_CLIENT_SECRET:string;GOOGLE_ADS_API_VERSION?:string;GOOGLE_ADS_LOGIN_CUSTOMER_ID?:string};
type Placement={stableKey:string;sourceView:string;resourceName:string;placement:string;displayName:string;placementType:string;targetUrl:string|null;campaignId:string|null;campaignName:string;campaignType:string;adGroupId:string|null;adGroupName:string;impressions:number;clicks:number;spend:number;conversions:number;videoViews:number};
type Job={id:string;google_customer_id:string;reporting_start_date:string;reporting_end_date:string;cancellation_requested:boolean;r2_object_key:string|null;next_offset:number;imported_rows:number};
type GoogleRow={performanceMaxPlacementView?:GooglePlacementView;detailPlacementView?:GooglePlacementView;campaign?:{id?:string;name?:string;advertisingChannelType?:string};adGroup?:{id?:string;name?:string};metrics?:{impressions?:string|number;clicks?:string|number;costMicros?:string|number;conversions?:string|number;videoViews?:string|number}};
type GooglePlacementView={resourceName?:string;placement?:string;displayName?:string;placementType?:string;groupPlacementTargetUrl?:string;targetUrl?:string};
const BATCH_SIZE=250;

const worker = {
  async fetch(request:Request,env:Env):Promise<Response>{
    if(!await authorized(request,env.WORKER_API_SECRET))return json({error:"Unauthorized"},401);
    const url=new URL(request.url); if(request.method!=="POST"||url.pathname!=="/placement-analysis/commands")return json({error:"Not found"},404);
    const body=await request.json<QueueMessage>(); if(!body.jobId||!/^\d{10}$/.test(body.accountId)||!["retrieve","next","all","cancel"].includes(body.command))return json({error:"Invalid placement command"},400);
    await env.PLACEMENT_QUEUE.send(body); return json({queued:true},202);
  },
  async queue(batch:MessageBatch<QueueMessage>,env:Env):Promise<void>{
    for(const message of batch.messages){try{if(message.body.command==="retrieve")await retrieve(message.body,env);else if(message.body.command==="cancel")await cancel(message.body,env);else await importBatch(message.body,env);message.ack();}catch(error){console.error(JSON.stringify({event:"placement_job_failed",jobId:message.body.jobId,error:error instanceof Error?error.message:String(error)}));await patchJob(env,message.body.jobId,{status:"failed",stage:"Placement analysis failed",error:error instanceof Error?error.message:String(error),finished_at:new Date().toISOString()});message.retry();}}
  }
};

export default worker;

async function retrieve(message:QueueMessage,env:Env){
  const job=await getJob(env,message.jobId);if(!job||job.cancellation_requested)return;
  await patchJob(env,message.jobId,{status:"running",stage:"Retrieving Google placement report",processed_rows:0,total_rows:null,error:null});
  const loginCustomerId=await resolveLoginCustomerId(env,message.accountId);const token=await accessToken(env);const [standard,pmax]=await Promise.all([
    googleRows(env,token,message.accountId,loginCustomerId,standardQuery(message.startDate,message.endDate),"detail_placement_view"),
    googleRows(env,token,message.accountId,loginCustomerId,pmaxQuery(message.startDate,message.endDate),"performance_max_placement_view")
  ]);
  const unique=new Map<string,Placement>();for(const row of [...standard,...pmax]){const existing=unique.get(row.stableKey);if(!existing||row.impressions>existing.impressions)unique.set(row.stableKey,row);}
  const latest=await getJob(env,message.jobId);if(!latest||latest.cancellation_requested)return;
  const rows=[...unique.values()].sort((a,b)=>b.impressions-a.impressions||a.stableKey.localeCompare(b.stableKey));const key=`placement-imports/${message.jobId}.json`;
  await env.PLACEMENT_IMPORTS.put(key,JSON.stringify(rows),{httpMetadata:{contentType:"application/json"},customMetadata:{expiresAt:new Date(Date.now()+7*86400000).toISOString()}});
  await patchJob(env,message.jobId,{r2_object_key:key,total_rows:rows.length,next_offset:0,imported_rows:0,source_expires_at:new Date(Date.now()+7*86400000).toISOString(),stage:"Saving first 250 placements"});
  await importBatch(message,env);
}

async function cancel(message:QueueMessage,env:Env){const job=await getJob(env,message.jobId);if(job?.r2_object_key)await env.PLACEMENT_IMPORTS.delete(job.r2_object_key);await patchJob(env,message.jobId,{status:"cancelled",stage:"Placement import stopped",finished_at:new Date().toISOString()});}

async function importBatch(message:QueueMessage,env:Env){
  const job=await getJob(env,message.jobId);if(!job||job.cancellation_requested||!job.r2_object_key)return;await patchJob(env,message.jobId,{status:"running",stage:job.next_offset===0?"Saving the first 250 placements":"Importing the next 250 placements"});const object=await env.PLACEMENT_IMPORTS.get(job.r2_object_key);if(!object)throw new Error("Temporary placement import expired. Start analysis again.");const rows=await object.json<Placement[]>();
  const slice=rows.slice(job.next_offset,job.next_offset+BATCH_SIZE);if(!slice.length){await complete(env,job,rows.length);return;}const runId=await upsertRun(env,message,rows,job.next_offset+slice.length>=rows.length);await insertRows(env,runId,slice);const next=job.next_offset+slice.length;const completeNow=next>=rows.length;await patchJob(env,message.jobId,{status:completeNow?"completed":"running",stage:completeNow?"Placement import completed":`${next.toLocaleString()} saved · ${(rows.length-next).toLocaleString()} remaining`,processed_rows:next,imported_rows:next,next_offset:next,total_rows:rows.length,finished_at:completeNow?new Date().toISOString():null});await patchRun(env,runId,{imported_count:next,total_available:rows.length,is_complete:completeNow,placement_count:next});if(completeNow){await env.PLACEMENT_IMPORTS.delete(job.r2_object_key);return;}await env.PLACEMENT_QUEUE.send({...message,command:"next"});
}

async function complete(env:Env,job:Job,total:number){await patchJob(env,job.id,{status:"completed",stage:"Placement analysis completed",processed_rows:total,imported_rows:total,next_offset:total,total_rows:total,finished_at:new Date().toISOString()});if(job.r2_object_key)await env.PLACEMENT_IMPORTS.delete(job.r2_object_key);}

async function upsertRun(env:Env,message:QueueMessage,rows:Placement[],complete:boolean){const campaignMap=new Map<string,{channelType:string;label:string;campaigns:Set<string>;placementCount:number;impressions:number;spend:number}>();for(const row of rows){const item=campaignMap.get(row.campaignType)??{channelType:row.campaignType,label:label(row.campaignType),campaigns:new Set<string>(),placementCount:0,impressions:0,spend:0};item.campaigns.add(row.campaignId??row.campaignName);item.placementCount++;item.impressions+=row.impressions;item.spend+=row.spend;campaignMap.set(row.campaignType,item);}const campaignTypes=[...campaignMap.values()].map(x=>({channelType:x.channelType,label:x.label,campaignCount:x.campaigns.size,placementCount:x.placementCount,impressions:x.impressions,spend:x.spend,available:x.placementCount>0}));const websites=rows.filter(x=>x.placementType==="WEBSITE");const payload={job_id:message.jobId,google_customer_id:message.accountId,customer_name:`Google Ads ${message.accountId}`,reporting_start_date:message.startDate,reporting_end_date:message.endDate,analyzed_at:new Date().toISOString(),campaign_types:campaignTypes,placement_count:0,total_impressions:rows.reduce((s,x)=>s+x.impressions,0),total_spend:rows.reduce((s,x)=>s+x.spend,0),unique_sites:new Set(websites.map(x=>x.placement)).size,top_sites:websites.slice(0,5).map((x,i)=>({id:`pending:${i}`,displayName:x.displayName,placement:x.placement,targetUrl:x.targetUrl,campaignName:x.campaignName,campaignType:x.campaignType,impressions:x.impressions})),imported_count:0,total_available:rows.length,is_complete:complete};const result=await supabase<Array<{id:number}>>(env,"ad_automation_placement_runs_v2?on_conflict=google_customer_id,reporting_start_date,reporting_end_date",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(payload)});return Number(result[0].id);}
async function insertRows(env:Env,runId:number,rows:Placement[]){const payload=rows.map(x=>({run_id:runId,stable_key:x.stableKey,source_view:x.sourceView,resource_name:x.resourceName,placement:x.placement,display_name:x.displayName,placement_type:x.placementType,target_url:x.targetUrl,campaign_id:x.campaignId,campaign_name:x.campaignName,campaign_type:x.campaignType,ad_group_id:x.adGroupId,ad_group_name:x.adGroupName,impressions:x.impressions,clicks:x.clicks,spend:x.spend,conversions:x.conversions,video_views:x.videoViews}));await supabase(env,"ad_automation_placement_rows_v2?on_conflict=run_id,stable_key",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(payload)});}
async function patchRun(env:Env,id:number,values:Record<string,unknown>){await supabase(env,`ad_automation_placement_runs_v2?id=eq.${id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(values)});}
async function getJob(env:Env,id:string){const rows=await supabase<Job[]>(env,`ad_automation_placement_jobs?id=eq.${encodeURIComponent(id)}&select=*&limit=1`);return rows[0]??null;}
async function patchJob(env:Env,id:string,values:Record<string,unknown>){await supabase(env,`ad_automation_placement_jobs?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({...values,updated_at:new Date().toISOString()})});}
async function supabase<T=unknown>(env:Env,path:string,init?:RequestInit):Promise<T>{const headers=new Headers(init?.headers);headers.set("apikey",env.SUPABASE_SECRET_KEY);headers.set("Authorization",`Bearer ${env.SUPABASE_SECRET_KEY}`);headers.set("Content-Type","application/json");const response=await fetch(`${env.SUPABASE_URL.replace(/\/$/,"")}/rest/v1/${path}`,{...init,headers});const text=await response.text();if(!response.ok)throw new Error(`Supabase ${response.status}: ${text.slice(0,500)}`);return(text?JSON.parse(text):null)as T;}
async function resolveLoginCustomerId(env:Env,cid:string){const row=await env.ACCOUNT_DIRECTORY.prepare("SELECT access_path FROM ad_accounts WHERE google_account_id = ? AND active = 1 LIMIT 1").bind(cid).first<{access_path:string|null}>();return row?.access_path?.replace(/\D/g,"")||env.GOOGLE_ADS_LOGIN_CUSTOMER_ID?.replace(/\D/g,"")||null;}
async function accessToken(env:Env){const body=new URLSearchParams({client_id:env.GOOGLE_ADS_CLIENT_ID,client_secret:env.GOOGLE_ADS_CLIENT_SECRET,refresh_token:env.GOOGLE_ADS_REFRESH_TOKEN,grant_type:"refresh_token"});const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});const json=await response.json<{access_token?:string;error_description?:string}>();if(!response.ok||!json.access_token)throw new Error(json.error_description||"Google OAuth refresh failed");return json.access_token;}
async function googleRows(env:Env,token:string,cid:string,login:string|null,query:string,sourceView:string):Promise<Placement[]>{const response=await fetch(`https://googleads.googleapis.com/${env.GOOGLE_ADS_API_VERSION||"v22"}/customers/${cid}/googleAds:searchStream`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"developer-token":env.GOOGLE_ADS_DEVELOPER_TOKEN,"content-type":"application/json",...(login?{"login-customer-id":login}:{})},body:JSON.stringify({query})});if(!response.ok)throw new Error(`Google Ads ${response.status}: ${(await response.text()).slice(0,500)}`);const batches=await response.json<Array<{results?:GoogleRow[]}>>();return batches.flatMap(x=>x.results??[]).map(x=>normalize(x,sourceView));}
function normalize(x:GoogleRow,sourceView:string):Placement{const p=sourceView==="performance_max_placement_view"?x.performanceMaxPlacementView:x.detailPlacementView;const campaign=x.campaign??{};const adGroup=x.adGroup??{};const placement=String(p?.placement??p?.displayName??"Unknown placement");const resource=String(p?.resourceName??`${sourceView}:${p?.placementType??"UNKNOWN"}:${placement}`);return{stableKey:`${sourceView}:${resource}`,sourceView,resourceName:resource,placement,displayName:String(p?.displayName??placement),placementType:String(p?.placementType??"UNKNOWN"),targetUrl:p?.groupPlacementTargetUrl??p?.targetUrl??null,campaignId:campaign.id?String(campaign.id):null,campaignName:String(campaign.name??(sourceView==="performance_max_placement_view"?"Performance Max":"Unknown campaign")),campaignType:String(campaign.advertisingChannelType??(sourceView==="performance_max_placement_view"?"PERFORMANCE_MAX":"UNKNOWN")),adGroupId:adGroup.id?String(adGroup.id):null,adGroupName:String(adGroup.name??(sourceView==="performance_max_placement_view"?"Performance Max":"Unknown ad group")),impressions:Number(x.metrics?.impressions??0),clicks:Number(x.metrics?.clicks??0),spend:Number(x.metrics?.costMicros??0)/1_000_000,conversions:Number(x.metrics?.conversions??0),videoViews:Number(x.metrics?.videoViews??0)};}
function standardQuery(start:string,end:string){return `SELECT detail_placement_view.resource_name, detail_placement_view.placement, detail_placement_view.display_name, detail_placement_view.placement_type, detail_placement_view.group_placement_target_url, campaign.id, campaign.name, campaign.advertising_channel_type, ad_group.id, ad_group.name, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions FROM detail_placement_view WHERE segments.date BETWEEN '${start}' AND '${end}' AND campaign.status != 'REMOVED' AND metrics.impressions > 0 ORDER BY metrics.impressions DESC`;}
function pmaxQuery(start:string,end:string){return `SELECT performance_max_placement_view.placement, performance_max_placement_view.display_name, performance_max_placement_view.placement_type, metrics.impressions FROM performance_max_placement_view WHERE segments.date BETWEEN '${start}' AND '${end}' AND metrics.impressions > 0 ORDER BY metrics.impressions DESC`;}
function label(value:string){if(value==="VIDEO")return"Video / YouTube";if(value==="PERFORMANCE_MAX")return"Performance Max";if(value==="DEMAND_GEN"||value==="DISCOVERY")return"Demand Gen";return value.toLowerCase().split("_").map(x=>x[0]?.toUpperCase()+x.slice(1)).join(" ");}
async function authorized(request:Request,secret:string){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??"";const encoder=new TextEncoder();const [left,right]=await Promise.all([crypto.subtle.digest("SHA-256",encoder.encode(token)),crypto.subtle.digest("SHA-256",encoder.encode(secret))]);const a=new Uint8Array(left);const b=new Uint8Array(right);let difference=0;for(let index=0;index<a.length;index++)difference|=a[index]^b[index];return difference===0&&token.length===secret.length;}
function json(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});}
