import {describe,expect,it} from 'vitest';
import {authenticate,sha256,type AuthEnv} from '../src/auth';
import {WORKFLOW_PROTOCOL} from '../src/protocol';

class Db{seen=new Set<string>();prepare(){return {bind:(jti:string)=>({run:async()=>{if(this.seen.has(jti))throw new Error('unique');this.seen.add(jti);}})}}}
const enc=new TextEncoder(),url=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
async function jwt(claims:Record<string,unknown>,key='delegation-key-that-is-long-enough') {const header=url(enc.encode(JSON.stringify({alg:'HS256',typ:'JWT'}))),payload=url(enc.encode(JSON.stringify(claims))),cryptoKey=await crypto.subtle.importKey('raw',enc.encode(key),{name:'HMAC',hash:'SHA-256'},false,['sign']),signature=url(new Uint8Array(await crypto.subtle.sign('HMAC',cryptoKey,enc.encode(`${header}.${payload}`))));return `${header}.${payload}.${signature}`;}
async function fixture(change:Record<string,unknown>={}){const now=2_000_000_000,payload={title:'draft'},requestHash=await sha256(JSON.stringify(payload)),base={iss:'digitalbee-dev',aud:'digitalbee-dev-workflows',sub:'ava',iat:now,exp:now+30,jti:crypto.randomUUID(),action:'changes_list',service_id:'123e4567-e89b-42d3-a456-426614174001',platform:'google',provider_account_id:'2315114913',mapping_revision:'map-1',request_hash:requestHash,employee_revision:7},claims={...base,...change};return {now,input:{protocol:WORKFLOW_PROTOCOL,action:base.action,subject:base.sub,employeeRevision:base.employee_revision,serviceId:base.service_id,platform:base.platform,providerAccountId:base.provider_account_id,mappingRevision:base.mapping_revision,requestHash:base.request_hash,delegation:await jwt(claims),payload}};}
const env=()=>({DB:new Db() as unknown as D1Database,DEPLOYMENT_TIER:'dev',WORKFLOW_SERVICE_TOKEN:'service-token',WORKFLOW_DELEGATION_KEY:'delegation-key-that-is-long-enough'} as AuthEnv);
describe('workflow authentication',()=>{
  it('accepts one exact, short-lived, request-bound delegation',async()=>{const f=await fixture();await expect(authenticate(env(),'Bearer service-token',f.input,f.now)).resolves.toMatchObject({subject:'ava',action:'changes_list'});});
  it.each([['wrong subject',{sub:'other'}],['wrong audience',{aud:'other'}],['expired',{exp:1}],['too long',{iat:1_999_999_900,exp:2_000_000_000}],['wrong action',{action:'publish'}],['wrong account',{provider_account_id:'999'}],['wrong mapping',{mapping_revision:'map-2'}],['wrong request hash',{request_hash:'0'.repeat(64)}]])('rejects %s',async(_label,change)=>{const f=await fixture(change);await expect(authenticate(env(),'Bearer service-token',f.input,f.now)).rejects.toThrow();});
  it('rejects missing bearer, non-DEV, extra fields, bad signature and replay',async()=>{const f=await fixture(),e=env();await expect(authenticate(e,undefined,f.input,f.now)).rejects.toThrow();await expect(authenticate({...e,DEPLOYMENT_TIER:'production'},'Bearer service-token',f.input,f.now)).rejects.toThrow();await expect(authenticate(e,'Bearer service-token',{...f.input,extra:true},f.now)).rejects.toThrow();await expect(authenticate(e,'Bearer service-token',{...f.input,delegation:f.input.delegation+'x'},f.now)).rejects.toThrow();await authenticate(e,'Bearer service-token',f.input,f.now);await expect(authenticate(e,'Bearer service-token',f.input,f.now)).rejects.toThrow('replayed');});
});
