import {sha256} from '../auth';import type {WorkflowRequest} from '../protocol';
type Row={id:string;subject_hash:string;service_id:string;platform:string;provider_account_id:string;mapping_revision:string;lock_version:number;payload_json:string;idempotency_key:string;created_at:number;updated_at:number};
const view=(row:Row)=>({id:row.id,service_id:row.service_id,platform:row.platform,provider_account_id:row.provider_account_id,mapping_revision:row.mapping_revision,status:'draft',lock_version:row.lock_version,payload:JSON.parse(row.payload_json),provider_execution_locked:true,created_at:new Date(row.created_at).toISOString(),updated_at:new Date(row.updated_at).toISOString(),allowed_next_actions:['campaign_workflow_get','campaign_operation_get','campaign_draft_save','campaign_draft_validate','campaign_action_prepare']});
export class M04Repository{
  constructor(private readonly db:D1Database){}private session(){return this.db.withSession('first-primary');}private async subject(request:WorkflowRequest){return sha256(request.subject);}
  async get(request:WorkflowRequest,id:string){const row=await this.session().prepare('SELECT * FROM dev_m04_drafts WHERE id=? AND subject_hash=? AND service_id=?').bind(id,await this.subject(request),request.serviceId).first<Row>();if(!row)throw new Error('not_found');return view(row);}
  async operation(request:WorkflowRequest,id:string){const db=this.session(),subject=await this.subject(request),revision=await db.prepare('SELECT r.* FROM dev_m04_revisions r JOIN dev_m04_drafts d ON d.id=r.draft_id WHERE (r.id=? OR r.idempotency_key=?) AND d.subject_hash=? AND d.service_id=?').bind(id,id,subject,request.serviceId).first<Record<string,unknown>>();if(revision)return revisionView(revision);const draft=await db.prepare('SELECT * FROM dev_m04_drafts WHERE (id=? OR idempotency_key=?) AND subject_hash=? AND service_id=?').bind(id,id,subject,request.serviceId).first<Row>();if(draft)return view(draft);throw new Error('not_found');}
  async save(request:WorkflowRequest,input:{id?:string;expected_lock_version?:number;idempotency_key:string;payload:Record<string,unknown>}){const db=this.session(),subject=await this.subject(request),existing=await db.prepare('SELECT * FROM dev_m04_drafts WHERE subject_hash=? AND service_id=? AND idempotency_key=?').bind(subject,request.serviceId,input.idempotency_key).first<Row>();if(existing)return view(existing);if(input.id){const current=await this.get(request,input.id) as {lock_version:number};if(current.lock_version!==input.expected_lock_version)throw new Error('lock_conflict');await db.prepare('UPDATE dev_m04_drafts SET payload_json=?,idempotency_key=?,lock_version=lock_version+1,updated_at=? WHERE id=? AND subject_hash=? AND service_id=? AND lock_version=?').bind(JSON.stringify(input.payload),input.idempotency_key,Date.now(),input.id,subject,request.serviceId,input.expected_lock_version).run();return this.get(request,input.id);}const id=crypto.randomUUID(),now=Date.now();await db.prepare('INSERT INTO dev_m04_drafts(id,subject_hash,service_id,platform,provider_account_id,mapping_revision,lock_version,payload_json,created_at,updated_at,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,subject,request.serviceId,request.platform,request.providerAccountId,request.mappingRevision,0,JSON.stringify(input.payload),now,now,input.idempotency_key).run();return this.get(request,id);}
  async validate(request:WorkflowRequest,id:string,key:string){const draft=await this.get(request,id) as {lock_version:number;payload:Record<string,unknown>},db=this.session(),existing=await db.prepare('SELECT * FROM dev_m04_revisions WHERE draft_id=? AND idempotency_key=?').bind(id,key).first<Record<string,unknown>>();if(existing)return revisionView(existing);const issues=validate(draft.payload),json=JSON.stringify(draft.payload),hash=await sha256(json),revisionId=crypto.randomUUID(),now=Date.now();await db.prepare('INSERT INTO dev_m04_revisions(id,draft_id,revision_number,payload_hash,payload_json,validation_json,created_at,idempotency_key) VALUES(?,?,?,?,?,?,?,?)').bind(revisionId,id,draft.lock_version+1,hash,json,JSON.stringify(issues),now,key).run();return revisionView({id:revisionId,draft_id:id,revision_number:draft.lock_version+1,payload_hash:hash,payload_json:json,validation_json:JSON.stringify(issues),created_at:now});}
}
function validate(payload:Record<string,unknown>){const issues:Array<{path:string;message:string;severity:'error'}>=[];for(const key of ['campaign_name','objective','destination','start_date','end_date','timezone','targeting','creatives'])if(payload[key]===undefined||payload[key]==='')issues.push({path:key,message:`${key} is required.`,severity:'error'});if(typeof payload.allocated_budget!=='number'||payload.allocated_budget<=0)issues.push({path:'allocated_budget',message:'allocated_budget must be positive.',severity:'error'});if(typeof payload.destination==='string'){try{if(new URL(payload.destination).protocol!=='https:')throw new Error();}catch{issues.push({path:'destination',message:'destination must be an HTTPS URL.',severity:'error'});}}return issues;}
const revisionView=(row:Record<string,unknown>)=>{const issues=JSON.parse(String(row.validation_json)) as unknown[];return {id:row.id,draft_id:row.draft_id,revision_number:row.revision_number,payload_hash:row.payload_hash,result:issues.length?'failed':'passed',issues,payload:JSON.parse(String(row.payload_json)),provider_execution_locked:true,created_at:new Date(Number(row.created_at)).toISOString()};};
