import { NextResponse } from "next/server";
import { getServerAuthSession } from "@/lib/auth/server-session";
import { buildDateRange } from "@/lib/reporting/date";
import { loadPlacementCacheRows } from "@/lib/placement-optimization/cache-client";
import { loadPlacementExclusionHistory } from "@/lib/placement-optimization/exclusion-history";
import { isSupabaseUnavailableError } from "@/lib/optimization/supabase-rest";

export const dynamic="force-dynamic"; export const runtime="nodejs";
export async function GET(request:Request){const session=await getServerAuthSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const url=new URL(request.url);const accountId=(url.searchParams.get("accountId")??"").replace(/\D/g,"");if(accountId.length!==10)return NextResponse.json({error:"A valid account is required."},{status:400});const range=buildDateRange(url.searchParams.get("startDate"),url.searchParams.get("endDate"));const page=Math.max(1,Number(url.searchParams.get("page")??1));const pageSize=Math.min(250,Math.max(1,Number(url.searchParams.get("pageSize")??20)));const campaignType=url.searchParams.get("campaignType")??undefined;const placementType=url.searchParams.get("placementType")??undefined;try{if(url.searchParams.get("view")==="excluded")return NextResponse.json(await loadPlacementExclusionHistory({customerId:accountId,page,pageSize,campaignType,placementType}));return NextResponse.json(await loadPlacementCacheRows({accountId,startDate:range.startDate,endDate:range.endDate,page,pageSize,campaignType,placementType}));}catch(error){if(isSupabaseUnavailableError(error))return NextResponse.json({code:error.code,error:error.message},{status:503});const code=(error as {code?:string}).code;return NextResponse.json({code,error:error instanceof Error?error.message:"Unable to load placement rows."},{status:code==="PLACEMENT_CACHE_NOT_READY"?409:500});}}
