import { mkdtempSync, rmSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";

const temporaryDirectory=mkdtempSync(join(tmpdir(),"placement-optimization-"));process.env.SEARCH_TERM_SQLITE_PATH=join(temporaryDirectory,"test.sqlite");
const require=createRequire(import.meta.url);const repository=require("../lib/placement-optimization/sqlite-repository") as typeof import("../lib/placement-optimization/sqlite-repository");
const base={campaignId:"1",campaignName:"Display",adGroupId:"2",adGroupName:"General",impressions:100,clicks:4,spend:12,conversions:0,videoViews:0,targetUrl:null,analysis:{classification:"Test risk",recommendedAction:"exclude" as const,confidence:90,reason:"Test placement",confirmationRequired:false,aiStatus:"rules_fallback" as const}};
try{
  repository.persistPlacements({customerId:"1234567890",customerName:"Test Account",startDate:"2026-07-01",endDate:"2026-07-31",refreshedAt:new Date().toISOString(),rows:Array.from({length:6},(_,index)=>({...base,resourceName:`resource-${index}`,placement:`example-${index}.com`,displayName:`Placement ${index}`,placementType:index===1?"YOUTUBE_VIDEO":"WEBSITE"}))});
  let dashboard=repository.loadPlacementDashboard({customerId:"1234567890",customerName:"Test Account",startDate:"2026-07-01",endDate:"2026-07-31",refreshedAt:new Date().toISOString()});const ids=dashboard.rows.map(row=>Number(row.id));
  const optimizer={id:"co-test",email:"co@example.com",role:"co"};const approver={id:"approver-test",email:"approver@example.com",role:"approver"};
  repository.saveOptimizerDecision({recommendationIds:[ids[0],ids[1]],decision:"exclude",reviewer:optimizer});repository.saveOptimizerDecision({recommendationIds:[ids[2]],decision:"keep",reviewer:optimizer});repository.saveOptimizerDecision({recommendationIds:[ids[3]],decision:"kiv",reviewer:optimizer});repository.saveOptimizerDecision({recommendationIds:[ids[4]],decision:"exclude",reviewer:optimizer});repository.saveOptimizerDecision({recommendationIds:[ids[5]],decision:"exclude",reviewer:optimizer});
  const approval=repository.savePlacementApproverDecision({recommendationIds:[ids[0],ids[1]],decision:"approved",reviewer:approver});if(approval.updated!==2||!("changeSetId" in approval)||!approval.changeSetId||!("reportId" in approval)||!approval.reportId)throw new Error("Approval did not create a change set and PM report.");const duplicate=repository.savePlacementApproverDecision({recommendationIds:[ids[0],ids[1]],decision:"approved",reviewer:approver});if(duplicate.updated!==0||duplicate.skipped!==2)throw new Error("Approval was not idempotent.");repository.savePlacementApproverDecision({recommendationIds:[ids[4]],decision:"rejected",reviewer:approver});repository.savePlacementApproverDecision({recommendationIds:[ids[5]],decision:"returned",reviewer:approver});
  dashboard=repository.loadPlacementDashboard({customerId:"1234567890",customerName:"Test Account",startDate:"2026-07-01",endDate:"2026-07-31",refreshedAt:new Date().toISOString()});if(dashboard.summary.approved!==2||dashboard.summary.kept!==1||dashboard.summary.kiv!==1||dashboard.summary.rejected!==1||dashboard.reports.length!==1||dashboard.reports[0].items.length!==2)throw new Error("Placement workflow counts or report snapshot are incorrect.");
  const db=new DatabaseSync(process.env.SEARCH_TERM_SQLITE_PATH);const sets=db.prepare("select count(*) count from ad_automation_placement_change_sets").get() as {count:number};const items=db.prepare("select count(*) count from ad_automation_placement_change_set_items").get() as {count:number};db.close();if(sets.count!==1||items.count!==2)throw new Error("Duplicate change-set data was created.");console.log("Placement optimization SQLite workflow test passed.");
}finally{rmSync(temporaryDirectory,{recursive:true,force:true});}
