import {sha256} from '../auth';import type {WorkflowRequest} from '../protocol';
type DraftRow={id:string;subject_hash:string;service_id:string;platform:string;provider_account_id:string;mapping_revision:string;lock_version:number;payload_json:string;idempotency_key:string;created_at:number;updated_at:number};
const view=(row:DraftRow)=>({id:row.id,service_id:row.service_id,platform:row.platform,account_identity:row.provider_account_id,mapping_revision:row.mapping_revision,status:'draft',lock_version:row.lock_version,payload:JSON.parse(row.payload_json),provider_execution_locked:true,created_at:new Date(row.created_at).toISOString(),updated_at:new Date(row.updated_at).toISOString()});
export class M03Repository{
  constructor(private readonly db:D1Database){}
  private session(){return this.db.withSession('first-primary');}
  private async subject(request:WorkflowRequest){return sha256(request.subject);}
  async list(request:WorkflowRequest,page:number,pageSize:number){const hash=await this.subject(request),offset=(page-1)*pageSize,{results}=await this.session().prepare('SELECT * FROM dev_m03_drafts WHERE subject_hash=? AND service_id=? ORDER BY updated_at DESC LIMIT ? OFFSET ?').bind(hash,request.serviceId,pageSize,offset).all<DraftRow>();return {requests:results.map(view),pagination:{page,page_size:pageSize},provider_execution_locked:true};}
  async get(request:WorkflowRequest,id:string){const row=await this.session().prepare('SELECT * FROM dev_m03_drafts WHERE id=? AND subject_hash=? AND service_id=?').bind(id,await this.subject(request),request.serviceId).first<DraftRow>();if(!row)throw new Error('not_found');return view(row);}
  async create(request:WorkflowRequest,payload:Record<string,unknown>){const db=this.session(),subject=await this.subject(request),key=String(payload.idempotency_key),existing=await db.prepare('SELECT * FROM dev_m03_drafts WHERE subject_hash=? AND service_id=? AND idempotency_key=?').bind(subject,request.serviceId,key).first<DraftRow>();if(existing)return view(existing);const now=Date.now(),id=crypto.randomUUID(),json=JSON.stringify(payload);await db.prepare('INSERT INTO dev_m03_drafts(id,subject_hash,service_id,platform,provider_account_id,mapping_revision,lock_version,payload_json,created_at,updated_at,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,subject,request.serviceId,request.platform,request.providerAccountId,request.mappingRevision,0,json,now,now,key).run();return this.get(request,id);}
  async revise(request:WorkflowRequest,payload:Record<string,unknown>&{id:string;expected_lock_version:number}){const current=await this.get(request,payload.id) as {lock_version:number};if(current.lock_version!==payload.expected_lock_version)throw new Error('lock_conflict');const db=this.session(),key=String(payload.idempotency_key),existing=await db.prepare('SELECT * FROM dev_m03_drafts WHERE id=? AND idempotency_key=?').bind(payload.id,key).first<DraftRow>();if(existing)return view(existing);const {id,expected_lock_version,...body}=payload;await db.prepare('UPDATE dev_m03_drafts SET payload_json=?,idempotency_key=?,lock_version=lock_version+1,updated_at=? WHERE id=? AND subject_hash=? AND service_id=? AND lock_version=?').bind(JSON.stringify(body),key,Date.now(),id,await this.subject(request),request.serviceId,expected_lock_version).run();return this.get(request,id);}
  async validate(request:WorkflowRequest,id:string,key:string){const draft=await this.get(request,id) as {lock_version:number;payload:Record<string,unknown>},db=this.session(),existing=await db.prepare('SELECT * FROM dev_m03_revisions WHERE draft_id=? AND idempotency_key=?').bind(id,key).first<Record<string,unknown>>();if(existing)return revisionView(existing);const issues=validateItems(draft.payload.items),json=JSON.stringify(draft.payload),hash=await sha256(json),revisionId=crypto.randomUUID(),revision=draft.lock_version+1,now=Date.now();await db.prepare('INSERT INTO dev_m03_revisions(id,draft_id,revision_number,payload_hash,payload_json,validation_json,created_at,idempotency_key) VALUES(?,?,?,?,?,?,?,?)').bind(revisionId,id,revision,hash,json,JSON.stringify(issues),now,key).run();return revisionView({id:revisionId,draft_id:id,revision_number:revision,payload_hash:hash,validation_json:JSON.stringify(issues),created_at:now});}
}
const revisionView=(row:Record<string,unknown>)=>{const validation=JSON.parse(String(row.validation_json)) as unknown[];return {id:row.id,draft_id:row.draft_id,revision_number:row.revision_number,payload_hash:row.payload_hash,result:validation.length?'failed':'passed',validation,provider_execution_locked:true,created_at:new Date(Number(row.created_at)).toISOString()};};
function validateItems(value:unknown){const items=Array.isArray(value)?value as Array<Record<string,unknown>>:[];return items.flatMap((item,index)=>{const proposed=item.proposed_value,type=item.value_type,valid=type==='null'?proposed===null:type==='json'?proposed!==undefined:typeof proposed===type;return valid?[]:[{path:`items.${index}.proposed_value`,message:`Value must match ${String(type)}.`,severity:'error'}];});}
