begin;

drop table if exists public.ad_automation_placement_decisions cascade;
drop table if exists public.ad_automation_placement_analysis_runs cascade;
drop table if exists public.ad_automation_placement_rows_v2 cascade;
drop table if exists public.ad_automation_placement_runs_v2 cascade;
drop table if exists public.ad_automation_placement_jobs cascade;

create table if not exists public.ad_automation_placement_exclusion_history (
  id bigint generated by default as identity primary key,
  google_customer_id text not null,
  campaign_id text not null,
  campaign_name text not null,
  campaign_type text not null,
  placement text not null,
  normalized_placement text not null,
  placement_type text not null,
  reviewer_user_id text not null,
  reviewer_role text not null,
  reporting_start_date date not null,
  reporting_end_date date not null,
  google_resource_name text,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (google_customer_id, campaign_id, placement_type, normalized_placement)
);

create index if not exists ad_placement_exclusion_history_account_idx
  on public.ad_automation_placement_exclusion_history (google_customer_id, published_at desc);

alter table public.ad_automation_placement_exclusion_history enable row level security;
revoke all on public.ad_automation_placement_exclusion_history from anon, authenticated;
grant select, insert, update, delete on public.ad_automation_placement_exclusion_history to service_role;
grant usage, select on sequence public.ad_automation_placement_exclusion_history_id_seq to service_role;

commit;
