begin;
create table if not exists public.ad_automation_search_term_analysis_runs (
 id bigint generated by default as identity primary key, google_customer_id text not null, customer_name text,
 reporting_start_date date not null, reporting_end_date date not null, analyzed_at timestamptz not null,
 recommendations jsonb not null check (jsonb_typeof(recommendations)='array'), created_at timestamptz not null default now(),
 unique(google_customer_id,analyzed_at)
);
create table if not exists public.ad_automation_search_term_decisions (
 id bigint generated by default as identity primary key, analysis_run_id bigint not null references public.ad_automation_search_term_analysis_runs(id),
 recommendation_key text not null, decision text, status text not null, reviewer_user_id text, reviewer_email text, reviewer_role text,
 reviewed_at timestamptz, google_ads_resource_name text, publish_error text, metadata jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now(),
 unique(analysis_run_id,recommendation_key)
);
create table if not exists public.ad_automation_placement_analysis_runs (
 id bigint generated by default as identity primary key, google_customer_id text not null, customer_name text,
 reporting_start_date date not null, reporting_end_date date not null, analyzed_at timestamptz not null,
 recommendations jsonb not null check (jsonb_typeof(recommendations)='array'), created_at timestamptz not null default now(),
 unique(google_customer_id,reporting_start_date,reporting_end_date)
);
create table if not exists public.ad_automation_placement_decisions (
 id bigint generated by default as identity primary key, analysis_run_id bigint not null references public.ad_automation_placement_analysis_runs(id),
 recommendation_key text not null, decision text, status text not null, reviewer_user_id text, reviewer_email text, reviewer_role text,
 reviewed_at timestamptz, google_ads_resource_name text, publish_error text, metadata jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now(),
 unique(analysis_run_id,recommendation_key)
);
create index if not exists ad_search_runs_account_idx on public.ad_automation_search_term_analysis_runs(google_customer_id,analyzed_at desc);
create index if not exists ad_search_decisions_run_idx on public.ad_automation_search_term_decisions(analysis_run_id,status);
create index if not exists ad_placement_runs_account_idx on public.ad_automation_placement_analysis_runs(google_customer_id,reporting_start_date,reporting_end_date);
create index if not exists ad_placement_decisions_run_idx on public.ad_automation_placement_decisions(analysis_run_id,status);
alter table public.ad_automation_search_term_analysis_runs enable row level security;
alter table public.ad_automation_search_term_decisions enable row level security;
alter table public.ad_automation_placement_analysis_runs enable row level security;
alter table public.ad_automation_placement_decisions enable row level security;
revoke all on public.ad_automation_search_term_analysis_runs,public.ad_automation_search_term_decisions,public.ad_automation_placement_analysis_runs,public.ad_automation_placement_decisions from anon,authenticated;
commit;
