-- M03-only provider-ready persistence. Provider execution remains deployment-locked.
-- Additive only: no M04, M05, reporting, authentication, credential, or legacy Google object is changed.

create table public.m03_ads_request_source_verifications (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique references public.m03_ads_change_requests(id) on delete cascade,
  source_kind text not null check (source_kind in ('m04_verified_launch','legacy_provider_adoption')),
  source_m04_plan_id bigint,
  source_m04_revision_id bigint,
  platform text not null check (platform in ('google','meta','tiktok')),
  provider_account_identity text not null check (btrim(provider_account_identity) <> ''),
  provider_campaign_identity text not null check (btrim(provider_campaign_identity) <> ''),
  source_revision_hash text check (source_revision_hash is null or source_revision_hash ~ '^[a-f0-9]{64}$'),
  evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(evidence) = 'object'),
  verified_by_id uuid not null,
  trusted_ip inet,
  trusted_user_agent text,
  idempotency_key text not null unique,
  verified_at timestamptz not null default clock_timestamp(),
  created_at timestamptz not null default clock_timestamp(),
  constraint m03_source_kind_shape check (
    (source_kind = 'm04_verified_launch' and source_m04_plan_id is not null and source_m04_revision_id is not null and source_revision_hash is not null)
    or
    (source_kind = 'legacy_provider_adoption' and source_m04_plan_id is null and source_m04_revision_id is null)
  )
);

create table public.m03_ads_provider_baseline_snapshots (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.m03_ads_change_requests(id) on delete cascade,
  revision_id uuid references public.m03_ads_change_request_revisions(id),
  platform text not null check (platform in ('google','meta','tiktok')),
  account_identity text not null,
  campaign_identity text not null,
  source text not null check (source in ('provider','legacy_google_compat','stored_snapshot')),
  canonical_payload jsonb not null check (jsonb_typeof(canonical_payload) = 'object'),
  payload_hash text not null check (payload_hash ~ '^[a-f0-9]{64}$'),
  captured_at timestamptz not null,
  freshness_expires_at timestamptz not null,
  captured_by_id uuid not null,
  trusted_ip inet,
  trusted_user_agent text,
  idempotency_key text not null,
  created_at timestamptz not null default clock_timestamp(),
  unique (request_id, idempotency_key)
);

create table public.m03_ads_provider_resource_mappings (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.m03_ads_change_requests(id) on delete cascade,
  item_id uuid not null unique references public.m03_ads_change_items(id) on delete cascade,
  platform text not null check (platform in ('google','meta','tiktok')),
  provider_resource_type text not null,
  previous_resource_identity text,
  replacement_resource_identity text,
  replacement_stage text not null default 'not_required' check (replacement_stage in (
    'not_required','replacement_planned','replacement_created_inactive','replacement_verified',
    'replacement_activated','previous_resource_disabled','completed','compensation_required'
  )),
  capability_registry_version integer not null check (capability_registry_version > 0),
  operation_plan jsonb not null default '[]'::jsonb check (jsonb_typeof(operation_plan) = 'array'),
  rollback_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(rollback_evidence) = 'object'),
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp()
);

alter table public.m03_ads_change_items
  add column if not exists capability_registry_version integer,
  add column if not exists mutation_mode text check (mutation_mode in ('direct_update','creative_replacement','unsupported')),
  add column if not exists replacement_stage text check (replacement_stage in (
    'not_required','replacement_planned','replacement_created_inactive','replacement_verified',
    'replacement_activated','previous_resource_disabled','completed','compensation_required'
  ));

alter table public.m03_ads_change_item_attempts
  add column if not exists revision_id uuid references public.m03_ads_change_request_revisions(id),
  add column if not exists operation_key text,
  add column if not exists replacement_stage text check (replacement_stage in (
    'not_required','replacement_planned','replacement_created_inactive','replacement_verified',
    'replacement_activated','previous_resource_disabled','completed','compensation_required'
  )),
  add column if not exists provider_request jsonb not null default '{}'::jsonb check (jsonb_typeof(provider_request) = 'object'),
  add column if not exists normalized_error jsonb not null default '{}'::jsonb check (jsonb_typeof(normalized_error) = 'object'),
  add column if not exists updated_at timestamptz not null default clock_timestamp();

create index m03_ads_source_verifications_request_idx on public.m03_ads_request_source_verifications (request_id, verified_at desc);
create index m03_ads_provider_baselines_request_idx on public.m03_ads_provider_baseline_snapshots (request_id, captured_at desc);
create index m03_ads_provider_resources_request_idx on public.m03_ads_provider_resource_mappings (request_id, updated_at desc);
create unique index m03_ads_change_item_attempts_operation_key_idx on public.m03_ads_change_item_attempts (operation_key) where operation_key is not null;

alter table public.m03_ads_request_source_verifications enable row level security;
alter table public.m03_ads_provider_baseline_snapshots enable row level security;
alter table public.m03_ads_provider_resource_mappings enable row level security;

revoke all on table public.m03_ads_request_source_verifications from public, anon, authenticated;
revoke all on table public.m03_ads_provider_baseline_snapshots from public, anon, authenticated;
revoke all on table public.m03_ads_provider_resource_mappings from public, anon, authenticated;
grant select, insert, update, delete on table public.m03_ads_request_source_verifications to service_role;
grant select, insert, update, delete on table public.m03_ads_provider_baseline_snapshots to service_role;
grant select, insert, update, delete on table public.m03_ads_provider_resource_mappings to service_role;
grant usage, select on sequence public.m03_ads_provider_resource_mappings_id_seq to service_role;

create or replace function public.m03_ads_record_source_verification_v1(
  p_request_id uuid, p_source_kind text, p_source_m04_plan_id bigint, p_source_m04_revision_id bigint,
  p_platform text, p_provider_account_identity text, p_provider_campaign_identity text,
  p_source_revision_hash text, p_evidence jsonb, p_actor_id uuid, p_trusted_ip inet,
  p_trusted_user_agent text, p_idempotency_key text
) returns public.m03_ads_request_source_verifications
language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_request public.m03_ads_change_requests; v_row public.m03_ads_request_source_verifications; v_actor record;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id,p_trusted_ip);
  select * into v_row from public.m03_ads_request_source_verifications where idempotency_key=p_idempotency_key;
  if found then return v_row; end if;
  select * into v_request from public.m03_ads_change_requests where id=p_request_id for update;
  if not found then raise exception 'change_request_not_found'; end if;
  if v_request.platform <> p_platform or v_request.account_identity <> p_provider_account_identity or v_request.campaign_identity <> p_provider_campaign_identity then raise exception 'source_identity_mismatch'; end if;
  if coalesce(v_request.source_m04_plan_id,0) <> coalesce(p_source_m04_plan_id,0) or coalesce(v_request.source_m04_revision_id,0) <> coalesce(p_source_m04_revision_id,0) then raise exception 'source_m04_reference_mismatch'; end if;
  insert into public.m03_ads_request_source_verifications(request_id,source_kind,source_m04_plan_id,source_m04_revision_id,platform,provider_account_identity,provider_campaign_identity,source_revision_hash,evidence,verified_by_id,trusted_ip,trusted_user_agent,idempotency_key)
  values(p_request_id,p_source_kind,p_source_m04_plan_id,p_source_m04_revision_id,p_platform,btrim(p_provider_account_identity),btrim(p_provider_campaign_identity),p_source_revision_hash,coalesce(p_evidence,'{}'::jsonb),p_actor_id,p_trusted_ip,left(p_trusted_user_agent,1000),p_idempotency_key)
  returning * into v_row;
  insert into public.m03_ads_change_events(request_id,event_type,to_status,actor_id,trusted_ip,trusted_user_agent,metadata)
  values(p_request_id,'post_launch_source_verified','draft',p_actor_id,p_trusted_ip,left(p_trusted_user_agent,1000),jsonb_build_object('source_verification_id',v_row.id,'source_kind',v_row.source_kind,'source_revision_hash',v_row.source_revision_hash));
  return v_row;
end $$;

create or replace function public.m03_ads_record_provider_baseline_v1(
  p_request_id uuid, p_revision_id uuid, p_platform text, p_account_identity text, p_campaign_identity text,
  p_source text, p_canonical_payload jsonb, p_payload_hash text, p_captured_at timestamptz,
  p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns public.m03_ads_provider_baseline_snapshots
language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_request public.m03_ads_change_requests; v_row public.m03_ads_provider_baseline_snapshots; v_actor record;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id,p_trusted_ip);
  select * into v_row from public.m03_ads_provider_baseline_snapshots where request_id=p_request_id and idempotency_key=p_idempotency_key;
  if found then return v_row; end if;
  select * into v_request from public.m03_ads_change_requests where id=p_request_id;
  if not found then raise exception 'change_request_not_found'; end if;
  if v_request.platform <> p_platform or v_request.account_identity <> p_account_identity or v_request.campaign_identity <> p_campaign_identity then raise exception 'baseline_identity_mismatch'; end if;
  if p_revision_id is not null and not exists(select 1 from public.m03_ads_change_request_revisions where id=p_revision_id and request_id=p_request_id) then raise exception 'revision_not_owned_by_request'; end if;
  if p_source not in ('provider','legacy_google_compat','stored_snapshot') then raise exception 'invalid_baseline_source'; end if;
  if jsonb_typeof(p_canonical_payload) <> 'object' or p_payload_hash !~ '^[a-f0-9]{64}$' then raise exception 'invalid_baseline_payload'; end if;
  insert into public.m03_ads_provider_baseline_snapshots(request_id,revision_id,platform,account_identity,campaign_identity,source,canonical_payload,payload_hash,captured_at,freshness_expires_at,captured_by_id,trusted_ip,trusted_user_agent,idempotency_key)
  values(p_request_id,p_revision_id,p_platform,p_account_identity,p_campaign_identity,p_source,p_canonical_payload,p_payload_hash,p_captured_at,p_captured_at + interval '15 minutes',p_actor_id,p_trusted_ip,left(p_trusted_user_agent,1000),p_idempotency_key)
  returning * into v_row;
  insert into public.m03_ads_change_events(request_id,revision_id,event_type,actor_id,trusted_ip,trusted_user_agent,metadata)
  values(p_request_id,p_revision_id,'provider_baseline_captured',p_actor_id,p_trusted_ip,left(p_trusted_user_agent,1000),jsonb_build_object('baseline_id',v_row.id,'payload_hash',p_payload_hash,'source',p_source));
  return v_row;
end $$;

create or replace function public.m03_ads_create_post_launch_change_request_v1(
  p_platform text, p_title text, p_reason text, p_client_id uuid, p_account_identity text,
  p_campaign_identity text, p_source_m04_plan_id bigint, p_source_m04_revision_id bigint,
  p_rollback_of_request_id uuid, p_supersedes_request_id uuid, p_items jsonb,
  p_source_kind text, p_source_revision_hash text, p_source_evidence jsonb,
  p_baseline_payload jsonb, p_baseline_hash text, p_baseline_captured_at timestamptz,
  p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns jsonb
language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_response jsonb; v_request_id uuid;
begin
  v_response := public.m03_ads_create_mock_change_request_v2(
    p_platform,p_title,p_reason,p_client_id,p_account_identity,p_campaign_identity,
    p_source_m04_plan_id,p_source_m04_revision_id,null,p_rollback_of_request_id,p_supersedes_request_id,
    p_items,p_actor_id,p_trusted_ip,p_trusted_user_agent,p_idempotency_key
  );
  v_request_id := (v_response->>'request_id')::uuid;
  perform public.m03_ads_record_source_verification_v1(
    v_request_id,p_source_kind,p_source_m04_plan_id,p_source_m04_revision_id,p_platform,
    p_account_identity,p_campaign_identity,p_source_revision_hash,p_source_evidence,p_actor_id,
    p_trusted_ip,p_trusted_user_agent,p_idempotency_key || ':source'
  );
  if p_source_kind='legacy_provider_adoption' then
    perform public.m03_ads_record_provider_baseline_v1(
      v_request_id,null,p_platform,p_account_identity,p_campaign_identity,'provider',p_baseline_payload,
      p_baseline_hash,p_baseline_captured_at,p_actor_id,p_trusted_ip,p_trusted_user_agent,p_idempotency_key || ':baseline'
    );
  end if;
  return v_response;
end $$;

create or replace function public.m03_ads_record_resource_mapping_v1(
  p_request_id uuid, p_item_id uuid, p_platform text, p_provider_resource_type text,
  p_previous_resource_identity text, p_replacement_resource_identity text, p_replacement_stage text,
  p_capability_registry_version integer, p_operation_plan jsonb, p_rollback_evidence jsonb,
  p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns public.m03_ads_provider_resource_mappings
language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_claim public.m03_ads_idempotency_claims; v_row public.m03_ads_provider_resource_mappings; v_actor record;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id,p_trusted_ip);
  select * into v_claim from public.m03_ads_idempotency_claims where action='resource_mapping_v1' and idempotency_key=p_idempotency_key;
  if found then select * into v_row from public.m03_ads_provider_resource_mappings where id=(v_claim.response_snapshot->>'mapping_id')::bigint; return v_row; end if;
  if not exists(select 1 from public.m03_ads_change_items where id=p_item_id and request_id=p_request_id) then raise exception 'change_item_not_owned_by_request'; end if;
  insert into public.m03_ads_provider_resource_mappings(request_id,item_id,platform,provider_resource_type,previous_resource_identity,replacement_resource_identity,replacement_stage,capability_registry_version,operation_plan,rollback_evidence)
  values(p_request_id,p_item_id,p_platform,p_provider_resource_type,p_previous_resource_identity,p_replacement_resource_identity,p_replacement_stage,p_capability_registry_version,coalesce(p_operation_plan,'[]'::jsonb),coalesce(p_rollback_evidence,'{}'::jsonb))
  on conflict(item_id) do update set replacement_resource_identity=coalesce(excluded.replacement_resource_identity,public.m03_ads_provider_resource_mappings.replacement_resource_identity),replacement_stage=excluded.replacement_stage,operation_plan=excluded.operation_plan,rollback_evidence=excluded.rollback_evidence,updated_at=clock_timestamp()
  returning * into v_row;
  update public.m03_ads_change_items set capability_registry_version=p_capability_registry_version,mutation_mode=case when p_replacement_stage='not_required' then 'direct_update' else 'creative_replacement' end,replacement_stage=p_replacement_stage where id=p_item_id;
  insert into public.m03_ads_change_events(request_id,event_type,actor_id,trusted_ip,trusted_user_agent,metadata)
  values(p_request_id,'provider_operation_plan_recorded',p_actor_id,p_trusted_ip,left(p_trusted_user_agent,1000),jsonb_build_object('mapping_id',v_row.id,'item_id',p_item_id,'replacement_stage',p_replacement_stage));
  insert into public.m03_ads_idempotency_claims(action,request_id,idempotency_key,response_snapshot) values('resource_mapping_v1',p_request_id,p_idempotency_key,jsonb_build_object('mapping_id',v_row.id));
  return v_row;
end $$;

create or replace function public.m03_ads_record_item_attempt_v1(
  p_request_id uuid, p_item_id uuid, p_revision_id uuid, p_action text, p_attempt_number integer,
  p_idempotency_key text, p_operation_key text, p_result text, p_replacement_stage text,
  p_provider_request jsonb, p_provider_result_evidence jsonb, p_readback_evidence jsonb,
  p_normalized_error jsonb, p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text
) returns public.m03_ads_change_item_attempts
language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_row public.m03_ads_change_item_attempts; v_actor record;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id,p_trusted_ip);
  select * into v_row from public.m03_ads_change_item_attempts where operation_key=p_operation_key;
  if found then return v_row; end if;
  if not exists(select 1 from public.m03_ads_change_items where id=p_item_id and request_id=p_request_id) then raise exception 'change_item_not_owned_by_request'; end if;
  if p_revision_id is not null and not exists(select 1 from public.m03_ads_change_request_revisions where id=p_revision_id and request_id=p_request_id) then raise exception 'revision_not_owned_by_request'; end if;
  insert into public.m03_ads_change_item_attempts(request_id,item_id,revision_id,action,attempt_number,idempotency_key,operation_key,result,replacement_stage,provider_request,provider_result_evidence,readback_evidence,normalized_error)
  values(p_request_id,p_item_id,p_revision_id,p_action,p_attempt_number,p_idempotency_key,p_operation_key,p_result,p_replacement_stage,coalesce(p_provider_request,'{}'::jsonb),coalesce(p_provider_result_evidence,'{}'::jsonb),coalesce(p_readback_evidence,'{}'::jsonb),coalesce(p_normalized_error,'{}'::jsonb))
  returning * into v_row;
  insert into public.m03_ads_change_events(request_id,revision_id,event_type,actor_id,trusted_ip,trusted_user_agent,metadata)
  values(p_request_id,p_revision_id,'provider_item_attempt_recorded',p_actor_id,p_trusted_ip,left(p_trusted_user_agent,1000),jsonb_build_object('attempt_id',v_row.id,'operation_key',p_operation_key,'result',p_result,'replacement_stage',p_replacement_stage));
  return v_row;
end $$;

do $$ declare f regprocedure; begin
  foreach f in array array[
    'public.m03_ads_record_source_verification_v1(uuid,text,bigint,bigint,text,text,text,text,jsonb,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_record_provider_baseline_v1(uuid,uuid,text,text,text,text,jsonb,text,timestamptz,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_create_post_launch_change_request_v1(text,text,text,uuid,text,text,bigint,bigint,uuid,uuid,jsonb,text,text,jsonb,jsonb,text,timestamptz,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_record_resource_mapping_v1(uuid,uuid,text,text,text,text,text,integer,jsonb,jsonb,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_record_item_attempt_v1(uuid,uuid,uuid,text,integer,text,text,text,text,jsonb,jsonb,jsonb,jsonb,uuid,inet,text)'::regprocedure
  ] loop
    execute format('revoke all on function %s from public,anon,authenticated',f);
    execute format('grant execute on function %s to service_role',f);
  end loop;
end $$;

comment on table public.m03_ads_request_source_verifications is 'Immutable M03 evidence that a request is post-launch: exact M04 handoff or fresh legacy-provider adoption.';
comment on table public.m03_ads_provider_baseline_snapshots is 'Fresh immutable provider baselines for M03 conflict preflight. Server/service-role only.';
comment on table public.m03_ads_provider_resource_mappings is 'M03 provider resource mapping and creative-replacement saga state. Provider execution remains locked.';
