-- Dashboard-only M03/M04 groundwork. Provider execution remains locked.
create extension if not exists pgcrypto with schema extensions;

create table public.m04_ads_approved_domains (
  id bigint generated by default as identity primary key,
  client_id uuid not null,
  domain text not null,
  is_active boolean not null default true,
  created_by_id uuid,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint m04_ads_approved_domains_domain_normalized check (domain = lower(trim(domain)) and domain <> ''),
  constraint m04_ads_approved_domains_client_domain_key unique (client_id, domain)
);

create table public.m04_ads_trusted_networks (
  id bigint generated by default as identity primary key,
  network cidr not null unique,
  label text not null,
  is_active boolean not null default true,
  created_by_id uuid,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp()
);

create table public.m04_ads_campaign_readiness_checks (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.m04_ads_campaign_plans(id),
  revision_id bigint not null references public.m04_ads_campaign_plan_revisions(id),
  revision_hash text not null,
  result text not null check (result in ('passed', 'failed', 'attention')),
  checks jsonb not null default '[]'::jsonb check (jsonb_typeof(checks) = 'array'),
  issues jsonb not null default '[]'::jsonb check (jsonb_typeof(issues) = 'array'),
  validation_snapshot jsonb not null default '{}'::jsonb check (jsonb_typeof(validation_snapshot) = 'object'),
  actor_id uuid not null,
  trusted_ip inet,
  trusted_user_agent text,
  request_idempotency_key text not null,
  created_at timestamptz not null default clock_timestamp(),
  constraint m04_ads_campaign_readiness_idempotency_key unique (plan_id, request_idempotency_key)
);

create index m04_ads_campaign_readiness_revision_idx
  on public.m04_ads_campaign_readiness_checks (revision_id, created_at desc);

create or replace function public.m04_ads_is_trusted_network(p_ip inet)
returns boolean language sql stable security invoker set search_path = public, pg_temp
as $$
  select coalesce(bool_or(p_ip <<= network), false)
  from public.m04_ads_trusted_networks
  where is_active;
$$;

create or replace function public.m04_ads_record_campaign_readiness(
  p_plan_id bigint,
  p_revision_id bigint,
  p_expected_revision_hash text,
  p_result text,
  p_checks jsonb,
  p_issues jsonb,
  p_validation_snapshot jsonb,
  p_actor_id uuid,
  p_trusted_ip inet,
  p_trusted_user_agent text,
  p_request_idempotency_key text
) returns public.m04_ads_campaign_readiness_checks
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_plan public.m04_ads_campaign_plans;
  v_revision public.m04_ads_campaign_plan_revisions;
  v_row public.m04_ads_campaign_readiness_checks;
begin
  if p_result not in ('passed', 'failed', 'attention') then
    raise exception 'invalid_readiness_result';
  end if;

  select * into v_plan from public.m04_ads_campaign_plans where id = p_plan_id for share;
  if not found then raise exception 'campaign_not_found'; end if;
  if v_plan.active_revision_id is distinct from p_revision_id then raise exception 'stale_campaign_revision'; end if;

  select * into v_revision from public.m04_ads_campaign_plan_revisions where id = p_revision_id and plan_id = p_plan_id;
  if not found or v_revision.payload_hash is distinct from p_expected_revision_hash then
    raise exception 'revision_hash_mismatch';
  end if;

  select * into v_row from public.m04_ads_campaign_readiness_checks
    where plan_id = p_plan_id and request_idempotency_key = p_request_idempotency_key;
  if found then return v_row; end if;

  insert into public.m04_ads_campaign_readiness_checks (
    plan_id, revision_id, revision_hash, result, checks, issues, validation_snapshot,
    actor_id, trusted_ip, trusted_user_agent, request_idempotency_key
  ) values (
    p_plan_id, p_revision_id, p_expected_revision_hash, p_result,
    coalesce(p_checks, '[]'::jsonb), coalesce(p_issues, '[]'::jsonb), coalesce(p_validation_snapshot, '{}'::jsonb),
    p_actor_id, p_trusted_ip, left(p_trusted_user_agent, 1000), p_request_idempotency_key
  ) returning * into v_row;

  insert into public.m04_ads_campaign_audit_events (
    plan_id, revision_id, event_type, actor_id, trusted_ip, trusted_user_agent, metadata
  ) values (
    p_plan_id, p_revision_id, 'readiness_checked', p_actor_id, p_trusted_ip,
    left(p_trusted_user_agent, 1000), jsonb_build_object('readiness_check_id', v_row.id, 'result', v_row.result)
  );
  return v_row;
end;
$$;

create table public.m03_ads_change_requests (
  id uuid primary key default gen_random_uuid(),
  platform text not null check (platform in ('google', 'meta', 'tiktok')),
  workflow_mode text not null default 'mock' check (workflow_mode = 'mock'),
  status text not null default 'draft' check (status in ('draft', 'validation_failed', 'awaiting_approval', 'approved', 'cancelled', 'provider_execution_locked')),
  title text not null,
  reason text not null,
  client_id uuid,
  account_identity text not null,
  campaign_identity text not null,
  source_m04_plan_id bigint references public.m04_ads_campaign_plans(id),
  source_m04_revision_id bigint references public.m04_ads_campaign_plan_revisions(id),
  created_by_id uuid not null,
  created_by_name text not null,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  lock_version bigint not null default 0
);

create table public.m03_ads_change_request_revisions (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.m03_ads_change_requests(id) on delete cascade,
  revision_number integer not null,
  canonical_payload jsonb not null check (jsonb_typeof(canonical_payload) = 'object'),
  payload_hash text not null,
  evidence jsonb not null default '{}'::jsonb,
  validation_issues jsonb not null default '[]'::jsonb,
  created_by_id uuid not null,
  created_at timestamptz not null default clock_timestamp(),
  unique (request_id, revision_number),
  unique (request_id, payload_hash)
);

create table public.m03_ads_change_items (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.m03_ads_change_requests(id) on delete cascade,
  entity_type text not null,
  entity_identity text not null,
  field_path text not null,
  baseline_value jsonb,
  proposed_value jsonb,
  evidence jsonb not null default '{}'::jsonb,
  validation_issues jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default clock_timestamp(),
  unique (request_id, entity_type, entity_identity, field_path)
);

create table public.m03_ads_validation_records (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.m03_ads_change_requests(id) on delete cascade,
  revision_id uuid not null references public.m03_ads_change_request_revisions(id),
  result text not null check (result in ('passed', 'failed')),
  issues jsonb not null default '[]'::jsonb,
  snapshot jsonb not null default '{}'::jsonb,
  validated_by_id uuid not null,
  created_at timestamptz not null default clock_timestamp()
);

create table public.m03_ads_change_approvals (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.m03_ads_change_requests(id) on delete cascade,
  revision_id uuid not null references public.m03_ads_change_request_revisions(id),
  revision_hash text not null,
  decision text not null default 'approved' check (decision = 'approved'),
  comment text,
  approved_by_id uuid not null,
  request_idempotency_key text not null,
  created_at timestamptz not null default clock_timestamp(),
  unique (request_id, request_idempotency_key)
);

create table public.m03_ads_change_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.m03_ads_change_requests(id) on delete cascade,
  revision_id uuid references public.m03_ads_change_request_revisions(id),
  event_type text not null,
  from_status text,
  to_status text,
  actor_id uuid,
  actor_name text,
  trusted_ip inet,
  trusted_user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp()
);

create table public.m03_ads_idempotency_claims (
  id bigint generated by default as identity primary key,
  action text not null,
  request_id uuid references public.m03_ads_change_requests(id) on delete cascade,
  idempotency_key text not null,
  response_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp(),
  unique (action, idempotency_key)
);

create table public.m03_ads_approved_domains (
  id bigint generated by default as identity primary key,
  client_id uuid,
  domain text not null,
  is_active boolean not null default true,
  created_by_id uuid,
  created_at timestamptz not null default clock_timestamp(),
  constraint m03_ads_approved_domains_normalized check (domain = lower(trim(domain)) and domain <> ''),
  unique (client_id, domain)
);

create table public.m03_ads_trusted_networks (
  id bigint generated by default as identity primary key,
  network cidr not null unique,
  label text not null,
  is_active boolean not null default true,
  created_by_id uuid,
  created_at timestamptz not null default clock_timestamp()
);

create index m03_ads_change_requests_status_idx on public.m03_ads_change_requests (status, updated_at desc);
create index m03_ads_change_events_request_idx on public.m03_ads_change_events (request_id, created_at asc);

create or replace function public.m03_ads_create_mock_change_request(
  p_platform text,
  p_title text,
  p_reason text,
  p_client_id uuid,
  p_account_identity text,
  p_campaign_identity text,
  p_source_m04_plan_id bigint,
  p_source_m04_revision_id bigint,
  p_items jsonb,
  p_actor_id uuid,
  p_actor_name text,
  p_idempotency_key text
) returns jsonb
language plpgsql security invoker set search_path = public, extensions, pg_temp
as $$
declare v_request public.m03_ads_change_requests; v_claim public.m03_ads_idempotency_claims; v_item jsonb;
begin
  if p_platform not in ('google','meta','tiktok') then raise exception 'unsupported_platform'; end if;
  select * into v_claim from public.m03_ads_idempotency_claims where action='create' and idempotency_key=p_idempotency_key;
  if found then return v_claim.response_snapshot; end if;
  insert into public.m03_ads_change_requests(platform,title,reason,client_id,account_identity,campaign_identity,source_m04_plan_id,source_m04_revision_id,created_by_id,created_by_name)
  values(p_platform,trim(p_title),trim(p_reason),p_client_id,trim(p_account_identity),trim(p_campaign_identity),p_source_m04_plan_id,p_source_m04_revision_id,p_actor_id,trim(p_actor_name)) returning * into v_request;
  for v_item in select value from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) loop
    insert into public.m03_ads_change_items(request_id,entity_type,entity_identity,field_path,baseline_value,proposed_value,evidence)
    values(v_request.id,v_item->>'entity_type',v_item->>'entity_identity',v_item->>'field_path',v_item->'baseline_value',v_item->'proposed_value',coalesce(v_item->'evidence','{}'::jsonb));
  end loop;
  insert into public.m03_ads_change_events(request_id,event_type,to_status,actor_id,actor_name,metadata)
    values(v_request.id,'request_created','draft',p_actor_id,p_actor_name,jsonb_build_object('workflow_mode','mock'));
  insert into public.m03_ads_idempotency_claims(action,request_id,idempotency_key,response_snapshot)
    values('create',v_request.id,p_idempotency_key,jsonb_build_object('request_id',v_request.id,'status',v_request.status,'workflow_mode','mock')) returning * into v_claim;
  return v_claim.response_snapshot;
end; $$;

create or replace function public.m03_ads_validate_mock_change_request(
  p_request_id uuid,
  p_actor_id uuid,
  p_actor_name text,
  p_idempotency_key text
) returns jsonb
language plpgsql security invoker set search_path = public, extensions, pg_temp
as $$
declare v_request public.m03_ads_change_requests; v_claim public.m03_ads_idempotency_claims; v_revision public.m03_ads_change_request_revisions; v_payload jsonb; v_issues jsonb; v_hash text; v_next integer;
begin
  select * into v_claim from public.m03_ads_idempotency_claims where action='validate' and idempotency_key=p_idempotency_key;
  if found then return v_claim.response_snapshot; end if;
  select * into v_request from public.m03_ads_change_requests where id=p_request_id for update;
  if not found then raise exception 'change_request_not_found'; end if;
  select coalesce(jsonb_agg(jsonb_build_object('entity_type',entity_type,'entity_identity',entity_identity,'field_path',field_path,'baseline_value',baseline_value,'proposed_value',proposed_value,'evidence',evidence) order by entity_type,entity_identity,field_path),'[]'::jsonb)
    into v_payload from public.m03_ads_change_items where request_id=p_request_id;
  v_issues := case when jsonb_array_length(v_payload)=0 then jsonb_build_array(jsonb_build_object('path','items','message','At least one proposed change is required.')) else '[]'::jsonb end;
  v_hash := encode(extensions.digest(convert_to(v_payload::text,'utf8'),'sha256'),'hex');
  select coalesce(max(revision_number),0)+1 into v_next from public.m03_ads_change_request_revisions where request_id=p_request_id;
  insert into public.m03_ads_change_request_revisions(request_id,revision_number,canonical_payload,payload_hash,evidence,validation_issues,created_by_id)
    values(p_request_id,v_next,jsonb_build_object('platform',v_request.platform,'workflow_mode','mock','items',v_payload),v_hash,jsonb_build_object('source_m04_plan_id',v_request.source_m04_plan_id,'source_m04_revision_id',v_request.source_m04_revision_id),v_issues,p_actor_id) returning * into v_revision;
  insert into public.m03_ads_validation_records(request_id,revision_id,result,issues,snapshot,validated_by_id)
    values(p_request_id,v_revision.id,case when jsonb_array_length(v_issues)=0 then 'passed' else 'failed' end,v_issues,jsonb_build_object('payload_hash',v_hash,'workflow_mode','mock'),p_actor_id);
  update public.m03_ads_change_requests set status=case when jsonb_array_length(v_issues)=0 then 'awaiting_approval' else 'validation_failed' end,updated_at=clock_timestamp(),lock_version=lock_version+1 where id=p_request_id returning * into v_request;
  insert into public.m03_ads_change_events(request_id,revision_id,event_type,from_status,to_status,actor_id,actor_name,metadata)
    values(p_request_id,v_revision.id,'request_validated','draft',v_request.status,p_actor_id,p_actor_name,jsonb_build_object('payload_hash',v_hash,'issues',v_issues));
  insert into public.m03_ads_idempotency_claims(action,request_id,idempotency_key,response_snapshot)
    values('validate',p_request_id,p_idempotency_key,jsonb_build_object('request_id',p_request_id,'revision_id',v_revision.id,'payload_hash',v_hash,'status',v_request.status,'issues',v_issues)) returning * into v_claim;
  return v_claim.response_snapshot;
end; $$;

create or replace function public.m03_ads_approve_mock_change_request(
  p_request_id uuid,
  p_actor_id uuid,
  p_actor_name text,
  p_comment text,
  p_idempotency_key text
) returns jsonb
language plpgsql security invoker set search_path = public, pg_temp
as $$
declare v_request public.m03_ads_change_requests; v_revision public.m03_ads_change_request_revisions; v_claim public.m03_ads_idempotency_claims; v_approval public.m03_ads_change_approvals;
begin
  select * into v_claim from public.m03_ads_idempotency_claims where action='approve' and idempotency_key=p_idempotency_key;
  if found then return v_claim.response_snapshot; end if;
  select * into v_request from public.m03_ads_change_requests where id=p_request_id for update;
  if not found then raise exception 'change_request_not_found'; end if;
  if v_request.workflow_mode <> 'mock' then raise exception 'provider_execution_locked'; end if;
  if v_request.status <> 'awaiting_approval' then raise exception 'request_not_ready_for_approval'; end if;
  select * into v_revision from public.m03_ads_change_request_revisions where request_id=p_request_id order by revision_number desc limit 1;
  insert into public.m03_ads_change_approvals(request_id,revision_id,revision_hash,comment,approved_by_id,request_idempotency_key)
    values(p_request_id,v_revision.id,v_revision.payload_hash,p_comment,p_actor_id,p_idempotency_key) returning * into v_approval;
  update public.m03_ads_change_requests set status='approved',updated_at=clock_timestamp(),lock_version=lock_version+1 where id=p_request_id;
  insert into public.m03_ads_change_events(request_id,revision_id,event_type,from_status,to_status,actor_id,actor_name,metadata)
    values(p_request_id,v_revision.id,'request_approved','awaiting_approval','approved',p_actor_id,p_actor_name,jsonb_build_object('approval_id',v_approval.id,'provider_execution_locked',true));
  insert into public.m03_ads_idempotency_claims(action,request_id,idempotency_key,response_snapshot)
    values('approve',p_request_id,p_idempotency_key,jsonb_build_object('request_id',p_request_id,'approval_id',v_approval.id,'status','approved','provider_execution_locked',true)) returning * into v_claim;
  return v_claim.response_snapshot;
end; $$;

do $$ declare t text; begin
  foreach t in array array[
    'm04_ads_approved_domains','m04_ads_trusted_networks','m04_ads_campaign_readiness_checks',
    'm03_ads_change_requests','m03_ads_change_request_revisions','m03_ads_change_items','m03_ads_validation_records',
    'm03_ads_change_approvals','m03_ads_change_events','m03_ads_idempotency_claims','m03_ads_approved_domains','m03_ads_trusted_networks'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from public, anon, authenticated', t);
    execute format('grant all on table public.%I to service_role', t);
  end loop;
end $$;

revoke all on function public.m04_ads_record_campaign_readiness(bigint,bigint,text,text,jsonb,jsonb,jsonb,uuid,inet,text,text) from public, anon, authenticated;
grant execute on function public.m04_ads_record_campaign_readiness(bigint,bigint,text,text,jsonb,jsonb,jsonb,uuid,inet,text,text) to service_role;
revoke all on function public.m04_ads_is_trusted_network(inet) from public, anon, authenticated;
grant execute on function public.m04_ads_is_trusted_network(inet) to service_role;
revoke all on function public.m03_ads_create_mock_change_request(text,text,text,uuid,text,text,bigint,bigint,jsonb,uuid,text,text) from public, anon, authenticated;
grant execute on function public.m03_ads_create_mock_change_request(text,text,text,uuid,text,text,bigint,bigint,jsonb,uuid,text,text) to service_role;
revoke all on function public.m03_ads_validate_mock_change_request(uuid,uuid,text,text) from public, anon, authenticated;
grant execute on function public.m03_ads_validate_mock_change_request(uuid,uuid,text,text) to service_role;
revoke all on function public.m03_ads_approve_mock_change_request(uuid,uuid,text,text,text) from public, anon, authenticated;
grant execute on function public.m03_ads_approve_mock_change_request(uuid,uuid,text,text,text) to service_role;
grant usage, select on all sequences in schema public to service_role;
