-- M03/M04 dashboard-only completion. Provider execution remains locked.
create schema if not exists m03_ads_internal;
revoke all on schema m03_ads_internal from public, anon, authenticated;

alter table public.m03_ads_change_requests
  drop constraint if exists m03_ads_change_requests_status_check;
alter table public.m03_ads_change_requests
  add constraint m03_ads_change_requests_status_check check (status in (
    'draft','validation_in_progress','validation_failed','awaiting_approval','approved',
    'conflict_detected','ready_to_publish','publishing','published','verification_in_progress',
    'verified','partially_completed','failed','reverted','cancelled','provider_execution_locked'
  ));

alter table public.m03_ads_change_requests
  add column if not exists source_m05_recommendation_ref text,
  add column if not exists rollback_of_request_id uuid references public.m03_ads_change_requests(id),
  add column if not exists supersedes_request_id uuid references public.m03_ads_change_requests(id);

alter table public.m03_ads_change_items
  add column if not exists value_type text not null default 'json'
    check (value_type in ('string','number','boolean','json','null')),
  add column if not exists platform_resource_mapping jsonb not null default '{}'::jsonb
    check (jsonb_typeof(platform_resource_mapping) = 'object'),
  add column if not exists provider_result_evidence jsonb not null default '{}'::jsonb
    check (jsonb_typeof(provider_result_evidence) = 'object'),
  add column if not exists readback_evidence jsonb not null default '{}'::jsonb
    check (jsonb_typeof(readback_evidence) = 'object');

alter table public.m03_ads_approved_domains
  add column if not exists label text,
  add column if not exists updated_by_id uuid,
  add column if not exists updated_at timestamptz not null default clock_timestamp();
alter table public.m03_ads_trusted_networks
  add column if not exists updated_by_id uuid,
  add column if not exists updated_at timestamptz not null default clock_timestamp();
alter table public.m04_ads_approved_domains
  add column if not exists label text,
  add column if not exists updated_by_id uuid;
alter table public.m04_ads_trusted_networks
  add column if not exists updated_by_id uuid;

create table public.m03_ads_change_item_attempts (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.m03_ads_change_requests(id) on delete cascade,
  item_id uuid not null references public.m03_ads_change_items(id) on delete cascade,
  action text not null check (action in ('publish','readback','rollback')),
  attempt_number integer not null check (attempt_number > 0),
  idempotency_key text not null,
  result text not null default 'provider_execution_locked'
    check (result in ('provider_execution_locked','pending','succeeded','failed')),
  provider_result_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(provider_result_evidence) = 'object'),
  readback_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(readback_evidence) = 'object'),
  created_at timestamptz not null default clock_timestamp(),
  unique (item_id, action, idempotency_key),
  unique (item_id, action, attempt_number)
);

create table public.m03_ads_admin_events (
  id bigint generated by default as identity primary key,
  action text not null,
  setting_kind text not null,
  setting_identity text not null,
  before_value jsonb,
  after_value jsonb,
  actor_id uuid not null,
  trusted_ip inet,
  trusted_user_agent text,
  idempotency_key text not null unique,
  created_at timestamptz not null default clock_timestamp()
);
create table public.m04_ads_admin_events (
  id bigint generated by default as identity primary key,
  action text not null,
  setting_kind text not null,
  setting_identity text not null,
  before_value jsonb,
  after_value jsonb,
  actor_id uuid not null,
  trusted_ip inet,
  trusted_user_agent text,
  idempotency_key text not null unique,
  created_at timestamptz not null default clock_timestamp()
);

create unique index if not exists m03_ads_operator_domain_unique_idx
  on public.m03_ads_approved_domains (domain) where client_id is null;
create index if not exists m03_ads_change_requests_page_idx
  on public.m03_ads_change_requests (updated_at desc, id);
create index if not exists m03_ads_change_requests_platform_status_idx
  on public.m03_ads_change_requests (platform, status, updated_at desc);
create index if not exists m03_ads_change_requests_m04_plan_idx
  on public.m03_ads_change_requests (source_m04_plan_id) where source_m04_plan_id is not null;
create index if not exists m03_ads_change_item_attempts_request_idx
  on public.m03_ads_change_item_attempts (request_id, created_at desc);
create index if not exists m03_ads_admin_events_created_idx on public.m03_ads_admin_events (created_at desc);
create index if not exists m04_ads_admin_events_created_idx on public.m04_ads_admin_events (created_at desc);
create index if not exists m03_ads_operator_domain_active_idx
  on public.m03_ads_approved_domains (domain) where client_id is null and is_active;

insert into public.m03_ads_approved_domains (client_id, domain, label, is_active)
values (null, 'locus-t.com.my', 'LOCUS-T operators', true), (null, 'digitalbee.ai', 'Digital Bee operators', true)
on conflict (domain) where client_id is null do update
set is_active = true, label = excluded.label, updated_at = clock_timestamp();

create or replace function m03_ads_internal.resolve_admin(p_actor_id uuid)
returns table(actor_name text, actor_email text)
language sql stable security definer set search_path = ''
as $$
  select coalesce(nullif(pg_catalog.btrim(a.full_name), ''), a.email), pg_catalog.lower(a.email)::text
  from public.ads_reporting_auth a
  where a.user_id = p_actor_id and a.is_active is true and a.role = 'admin'
$$;

create or replace function m03_ads_internal.resolve_operator(p_actor_id uuid, p_trusted_ip inet)
returns table(actor_name text, actor_email text)
language plpgsql stable security definer set search_path = ''
as $$
begin
  return query
  select coalesce(nullif(pg_catalog.btrim(a.full_name), ''), a.email), pg_catalog.lower(a.email)::text
  from public.ads_reporting_auth a
  where a.user_id = p_actor_id
    and a.is_active is true
    and a.role = 'admin'
    and exists (
      select 1 from public.m03_ads_approved_domains d
      where d.client_id is null and d.is_active is true
        and d.domain = pg_catalog.split_part(pg_catalog.lower(a.email), '@', 2)
    )
    and exists (
      select 1 from public.m03_ads_trusted_networks n
      where n.is_active is true and p_trusted_ip <<= n.network
    );
  if not found then raise exception 'operator_domain_or_trusted_network_not_approved' using errcode = '42501'; end if;
end;
$$;

create or replace function public.m03_ads_assert_operator_v1(
  p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text
) returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare v_actor record;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id, p_trusted_ip);
  return pg_catalog.jsonb_build_object('actor_id', p_actor_id, 'actor_name', v_actor.actor_name, 'approved', true);
end;
$$;

create or replace function public.m03_ads_create_mock_change_request_v2(
  p_platform text, p_title text, p_reason text, p_client_id uuid, p_account_identity text,
  p_campaign_identity text, p_source_m04_plan_id bigint, p_source_m04_revision_id bigint,
  p_source_m05_recommendation_ref text, p_rollback_of_request_id uuid, p_supersedes_request_id uuid,
  p_items jsonb, p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_request public.m03_ads_change_requests; v_claim public.m03_ads_idempotency_claims; v_item jsonb; v_actor record; v_response jsonb;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id, p_trusted_ip);
  if p_platform not in ('google','meta','tiktok') then raise exception 'unsupported_platform'; end if;
  if pg_catalog.jsonb_typeof(p_items) <> 'array' or pg_catalog.jsonb_array_length(p_items) = 0 then raise exception 'at_least_one_change_item_required'; end if;
  select * into v_claim from public.m03_ads_idempotency_claims where action='create_v2' and idempotency_key=p_idempotency_key;
  if found then return v_claim.response_snapshot; end if;
  insert into public.m03_ads_change_requests(platform,title,reason,client_id,account_identity,campaign_identity,source_m04_plan_id,source_m04_revision_id,source_m05_recommendation_ref,rollback_of_request_id,supersedes_request_id,created_by_id,created_by_name)
  values(p_platform,pg_catalog.btrim(p_title),pg_catalog.btrim(p_reason),p_client_id,pg_catalog.btrim(p_account_identity),pg_catalog.btrim(p_campaign_identity),p_source_m04_plan_id,p_source_m04_revision_id,nullif(pg_catalog.btrim(p_source_m05_recommendation_ref),''),p_rollback_of_request_id,p_supersedes_request_id,p_actor_id,v_actor.actor_name) returning * into v_request;
  for v_item in select value from pg_catalog.jsonb_array_elements(p_items) loop
    insert into public.m03_ads_change_items(request_id,entity_type,entity_identity,field_path,value_type,baseline_value,proposed_value,evidence,platform_resource_mapping)
    values(v_request.id,v_item->>'entity_type',v_item->>'entity_identity',v_item->>'field_path',coalesce(v_item->>'value_type','json'),v_item->'baseline_value',v_item->'proposed_value',coalesce(v_item->'evidence','{}'::jsonb),coalesce(v_item->'platform_resource_mapping','{}'::jsonb));
  end loop;
  insert into public.m03_ads_change_events(request_id,event_type,to_status,actor_id,actor_name,trusted_ip,trusted_user_agent,metadata)
  values(v_request.id,'request_created','draft',p_actor_id,v_actor.actor_name,p_trusted_ip,left(p_trusted_user_agent,1000),pg_catalog.jsonb_build_object('workflow_mode','mock','source_m05_recommendation_ref',v_request.source_m05_recommendation_ref));
  v_response := pg_catalog.jsonb_build_object('request_id',v_request.id,'status',v_request.status,'workflow_mode','mock','lock_version',v_request.lock_version);
  insert into public.m03_ads_idempotency_claims(action,request_id,idempotency_key,response_snapshot) values('create_v2',v_request.id,p_idempotency_key,v_response);
  return v_response;
end;
$$;

create or replace function public.m03_ads_edit_mock_change_request_v2(
  p_request_id uuid, p_expected_lock_version bigint, p_title text, p_reason text,
  p_source_m04_plan_id bigint, p_source_m04_revision_id bigint, p_source_m05_recommendation_ref text,
  p_rollback_of_request_id uuid, p_supersedes_request_id uuid, p_items jsonb,
  p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_request public.m03_ads_change_requests; v_claim public.m03_ads_idempotency_claims; v_item jsonb; v_actor record; v_response jsonb;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id,p_trusted_ip);
  select * into v_claim from public.m03_ads_idempotency_claims where action='edit_v2' and idempotency_key=p_idempotency_key;
  if found then return v_claim.response_snapshot; end if;
  select * into v_request from public.m03_ads_change_requests where id=p_request_id for update;
  if not found then raise exception 'change_request_not_found'; end if;
  if v_request.status not in ('draft','validation_failed') then raise exception 'only_draft_requests_can_be_edited'; end if;
  if v_request.lock_version <> p_expected_lock_version then raise exception 'stale_change_request_version'; end if;
  if pg_catalog.jsonb_typeof(p_items) <> 'array' or pg_catalog.jsonb_array_length(p_items)=0 then raise exception 'at_least_one_change_item_required'; end if;
  update public.m03_ads_change_requests set title=pg_catalog.btrim(p_title),reason=pg_catalog.btrim(p_reason),source_m04_plan_id=p_source_m04_plan_id,source_m04_revision_id=p_source_m04_revision_id,source_m05_recommendation_ref=nullif(pg_catalog.btrim(p_source_m05_recommendation_ref),''),rollback_of_request_id=p_rollback_of_request_id,supersedes_request_id=p_supersedes_request_id,status='draft',updated_at=clock_timestamp(),lock_version=lock_version+1 where id=p_request_id returning * into v_request;
  delete from public.m03_ads_change_items where request_id=p_request_id;
  for v_item in select value from pg_catalog.jsonb_array_elements(p_items) loop
    insert into public.m03_ads_change_items(request_id,entity_type,entity_identity,field_path,value_type,baseline_value,proposed_value,evidence,platform_resource_mapping)
    values(p_request_id,v_item->>'entity_type',v_item->>'entity_identity',v_item->>'field_path',coalesce(v_item->>'value_type','json'),v_item->'baseline_value',v_item->'proposed_value',coalesce(v_item->'evidence','{}'::jsonb),coalesce(v_item->'platform_resource_mapping','{}'::jsonb));
  end loop;
  insert into public.m03_ads_change_events(request_id,event_type,from_status,to_status,actor_id,actor_name,trusted_ip,trusted_user_agent,metadata)
  values(p_request_id,'request_edited',null,'draft',p_actor_id,v_actor.actor_name,p_trusted_ip,left(p_trusted_user_agent,1000),pg_catalog.jsonb_build_object('lock_version',v_request.lock_version));
  v_response:=pg_catalog.jsonb_build_object('request_id',p_request_id,'status','draft','lock_version',v_request.lock_version);
  insert into public.m03_ads_idempotency_claims(action,request_id,idempotency_key,response_snapshot) values('edit_v2',p_request_id,p_idempotency_key,v_response);
  return v_response;
end;
$$;

create or replace function public.m03_ads_validate_mock_change_request_v2(
  p_request_id uuid, p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_request public.m03_ads_change_requests; v_claim public.m03_ads_idempotency_claims; v_revision public.m03_ads_change_request_revisions; v_actor record; v_payload jsonb; v_issues jsonb; v_hash text; v_next integer; v_from text; v_response jsonb;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id,p_trusted_ip);
  select * into v_claim from public.m03_ads_idempotency_claims where action='validate_v2' and idempotency_key=p_idempotency_key;
  if found then return v_claim.response_snapshot; end if;
  select * into v_request from public.m03_ads_change_requests where id=p_request_id for update;
  if not found then raise exception 'change_request_not_found'; end if;
  if v_request.status not in ('draft','validation_failed') then raise exception 'request_not_editable_for_validation'; end if;
  v_from:=v_request.status;
  update public.m03_ads_change_requests set status='validation_in_progress',updated_at=clock_timestamp() where id=p_request_id;
  insert into public.m03_ads_change_events(request_id,event_type,from_status,to_status,actor_id,actor_name,trusted_ip,trusted_user_agent)
  values(p_request_id,'validation_started',v_from,'validation_in_progress',p_actor_id,v_actor.actor_name,p_trusted_ip,left(p_trusted_user_agent,1000));
  select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('entity_type',entity_type,'entity_identity',entity_identity,'field_path',field_path,'value_type',value_type,'baseline_value',baseline_value,'proposed_value',proposed_value,'evidence',evidence,'platform_resource_mapping',platform_resource_mapping) order by entity_type,entity_identity,field_path),'[]'::jsonb) into v_payload from public.m03_ads_change_items where request_id=p_request_id;
  v_issues:=case when pg_catalog.jsonb_array_length(v_payload)=0 then pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object('path','items','message','At least one proposed change is required.','severity','error')) else '[]'::jsonb end;
  v_payload:=pg_catalog.jsonb_build_object('platform',v_request.platform,'workflow_mode','mock','account_identity',v_request.account_identity,'campaign_identity',v_request.campaign_identity,'source_m04_plan_id',v_request.source_m04_plan_id,'source_m04_revision_id',v_request.source_m04_revision_id,'source_m05_recommendation_ref',v_request.source_m05_recommendation_ref,'items',v_payload);
  v_hash:=pg_catalog.encode(extensions.digest(pg_catalog.convert_to(v_payload::text,'utf8'),'sha256'),'hex');
  select coalesce(max(revision_number),0)+1 into v_next from public.m03_ads_change_request_revisions where request_id=p_request_id;
  insert into public.m03_ads_change_request_revisions(request_id,revision_number,canonical_payload,payload_hash,evidence,validation_issues,created_by_id)
  values(p_request_id,v_next,v_payload,v_hash,pg_catalog.jsonb_build_object('trusted_ip',p_trusted_ip,'source_m05_recommendation_ref',v_request.source_m05_recommendation_ref),v_issues,p_actor_id) returning * into v_revision;
  insert into public.m03_ads_validation_records(request_id,revision_id,result,issues,snapshot,validated_by_id) values(p_request_id,v_revision.id,case when pg_catalog.jsonb_array_length(v_issues)=0 then 'passed' else 'failed' end,v_issues,pg_catalog.jsonb_build_object('payload_hash',v_hash,'workflow_mode','mock','provider_execution_locked',true),p_actor_id);
  update public.m03_ads_change_requests set status=case when pg_catalog.jsonb_array_length(v_issues)=0 then 'awaiting_approval' else 'validation_failed' end,updated_at=clock_timestamp(),lock_version=lock_version+1 where id=p_request_id returning * into v_request;
  insert into public.m03_ads_change_events(request_id,revision_id,event_type,from_status,to_status,actor_id,actor_name,trusted_ip,trusted_user_agent,metadata) values(p_request_id,v_revision.id,'request_validated','validation_in_progress',v_request.status,p_actor_id,v_actor.actor_name,p_trusted_ip,left(p_trusted_user_agent,1000),pg_catalog.jsonb_build_object('payload_hash',v_hash,'issues',v_issues));
  v_response:=pg_catalog.jsonb_build_object('request_id',p_request_id,'revision_id',v_revision.id,'payload_hash',v_hash,'status',v_request.status,'issues',v_issues,'lock_version',v_request.lock_version);
  insert into public.m03_ads_idempotency_claims(action,request_id,idempotency_key,response_snapshot) values('validate_v2',p_request_id,p_idempotency_key,v_response);
  return v_response;
end;
$$;

create or replace function public.m03_ads_approve_mock_change_request_v2(
  p_request_id uuid, p_comment text, p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_request public.m03_ads_change_requests; v_revision public.m03_ads_change_request_revisions; v_claim public.m03_ads_idempotency_claims; v_approval public.m03_ads_change_approvals; v_actor record; v_response jsonb;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id,p_trusted_ip);
  select * into v_claim from public.m03_ads_idempotency_claims where action='approve_v2' and idempotency_key=p_idempotency_key;
  if found then return v_claim.response_snapshot; end if;
  select * into v_request from public.m03_ads_change_requests where id=p_request_id for update;
  if not found then raise exception 'change_request_not_found'; end if;
  if v_request.workflow_mode <> 'mock' then raise exception 'provider_execution_locked'; end if;
  if v_request.status <> 'awaiting_approval' then raise exception 'request_not_ready_for_approval'; end if;
  select * into v_revision from public.m03_ads_change_request_revisions where request_id=p_request_id order by revision_number desc limit 1;
  insert into public.m03_ads_change_approvals(request_id,revision_id,revision_hash,comment,approved_by_id,request_idempotency_key) values(p_request_id,v_revision.id,v_revision.payload_hash,p_comment,p_actor_id,p_idempotency_key) returning * into v_approval;
  update public.m03_ads_change_requests set status='approved',updated_at=clock_timestamp(),lock_version=lock_version+1 where id=p_request_id returning * into v_request;
  insert into public.m03_ads_change_events(request_id,revision_id,event_type,from_status,to_status,actor_id,actor_name,trusted_ip,trusted_user_agent,metadata) values(p_request_id,v_revision.id,'request_approved','awaiting_approval','approved',p_actor_id,v_actor.actor_name,p_trusted_ip,left(p_trusted_user_agent,1000),pg_catalog.jsonb_build_object('approval_id',v_approval.id,'provider_execution_locked',true));
  v_response:=pg_catalog.jsonb_build_object('request_id',p_request_id,'approval_id',v_approval.id,'status','approved','provider_execution_locked',true,'lock_version',v_request.lock_version);
  insert into public.m03_ads_idempotency_claims(action,request_id,idempotency_key,response_snapshot) values('approve_v2',p_request_id,p_idempotency_key,v_response);
  return v_response;
end;
$$;

create or replace function public.m03_ads_cancel_mock_change_request_v2(
  p_request_id uuid, p_comment text, p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_request public.m03_ads_change_requests; v_claim public.m03_ads_idempotency_claims; v_actor record; v_from text; v_response jsonb;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id,p_trusted_ip);
  select * into v_claim from public.m03_ads_idempotency_claims where action='cancel_v2' and idempotency_key=p_idempotency_key;
  if found then return v_claim.response_snapshot; end if;
  select * into v_request from public.m03_ads_change_requests where id=p_request_id for update;
  if not found then raise exception 'change_request_not_found'; end if;
  if v_request.status in ('approved','cancelled') then raise exception 'request_cannot_be_cancelled'; end if;
  v_from:=v_request.status;
  update public.m03_ads_change_requests set status='cancelled',updated_at=clock_timestamp(),lock_version=lock_version+1 where id=p_request_id returning * into v_request;
  insert into public.m03_ads_change_events(request_id,event_type,from_status,to_status,actor_id,actor_name,trusted_ip,trusted_user_agent,metadata) values(p_request_id,'request_cancelled',v_from,'cancelled',p_actor_id,v_actor.actor_name,p_trusted_ip,left(p_trusted_user_agent,1000),pg_catalog.jsonb_build_object('comment',p_comment));
  v_response:=pg_catalog.jsonb_build_object('request_id',p_request_id,'status','cancelled','lock_version',v_request.lock_version);
  insert into public.m03_ads_idempotency_claims(action,request_id,idempotency_key,response_snapshot) values('cancel_v2',p_request_id,p_idempotency_key,v_response);
  return v_response;
end;
$$;

create or replace function public.m03_ads_set_workflow_setting_v1(
  p_kind text, p_value text, p_label text, p_client_id uuid, p_is_active boolean,
  p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_actor record; v_before jsonb; v_after jsonb; v_row_id bigint; v_existing public.m03_ads_admin_events;
begin
  select * into v_actor from m03_ads_internal.resolve_admin(p_actor_id);
  if not found then raise exception 'active_administrator_required' using errcode='42501'; end if;
  select * into v_existing from public.m03_ads_admin_events where idempotency_key=p_idempotency_key;
  if found then return v_existing.after_value; end if;
  if p_kind='operator_domain' then
    select pg_catalog.to_jsonb(d.*),d.id into v_before,v_row_id from public.m03_ads_approved_domains d where d.client_id is null and d.domain=pg_catalog.lower(pg_catalog.btrim(p_value)) for update;
    if v_row_id is null then insert into public.m03_ads_approved_domains(client_id,domain,label,is_active,created_by_id,updated_by_id) values(null,pg_catalog.lower(pg_catalog.btrim(p_value)),p_label,p_is_active,p_actor_id,p_actor_id) returning id into v_row_id;
    else update public.m03_ads_approved_domains set label=p_label,is_active=p_is_active,updated_by_id=p_actor_id,updated_at=clock_timestamp() where id=v_row_id; end if;
    select pg_catalog.to_jsonb(d.*) into v_after from public.m03_ads_approved_domains d where d.id=v_row_id;
  elsif p_kind='trusted_network' then
    select pg_catalog.to_jsonb(n.*),n.id into v_before,v_row_id from public.m03_ads_trusted_networks n where n.network=p_value::cidr for update;
    if v_row_id is null then insert into public.m03_ads_trusted_networks(network,label,is_active,created_by_id,updated_by_id) values(p_value::cidr,coalesce(nullif(p_label,''),p_value),p_is_active,p_actor_id,p_actor_id) returning id into v_row_id;
    else update public.m03_ads_trusted_networks set label=coalesce(nullif(p_label,''),label),is_active=p_is_active,updated_by_id=p_actor_id,updated_at=clock_timestamp() where id=v_row_id; end if;
    select pg_catalog.to_jsonb(n.*) into v_after from public.m03_ads_trusted_networks n where n.id=v_row_id;
  else raise exception 'unsupported_m03_setting_kind'; end if;
  insert into public.m03_ads_admin_events(action,setting_kind,setting_identity,before_value,after_value,actor_id,trusted_ip,trusted_user_agent,idempotency_key) values(case when v_before is null then 'created' when p_is_active then 'activated_or_updated' else 'deactivated' end,p_kind,p_value,v_before,v_after,p_actor_id,p_trusted_ip,left(p_trusted_user_agent,1000),p_idempotency_key);
  return v_after;
end;
$$;

create or replace function public.m04_ads_set_workflow_setting_v1(
  p_kind text, p_value text, p_label text, p_client_id uuid, p_is_active boolean,
  p_actor_id uuid, p_trusted_ip inet, p_trusted_user_agent text, p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_actor record; v_before jsonb; v_after jsonb; v_row_id bigint; v_existing public.m04_ads_admin_events;
begin
  select * into v_actor from m03_ads_internal.resolve_admin(p_actor_id);
  if not found then raise exception 'active_administrator_required' using errcode='42501'; end if;
  select * into v_existing from public.m04_ads_admin_events where idempotency_key=p_idempotency_key;
  if found then return v_existing.after_value; end if;
  if p_kind='destination_domain' then
    if p_client_id is null then raise exception 'client_required_for_destination_domain'; end if;
    select pg_catalog.to_jsonb(d.*),d.id into v_before,v_row_id from public.m04_ads_approved_domains d where d.client_id=p_client_id and d.domain=pg_catalog.lower(pg_catalog.btrim(p_value)) for update;
    if v_row_id is null then insert into public.m04_ads_approved_domains(client_id,domain,label,is_active,created_by_id,updated_by_id) values(p_client_id,pg_catalog.lower(pg_catalog.btrim(p_value)),p_label,p_is_active,p_actor_id,p_actor_id) returning id into v_row_id;
    else update public.m04_ads_approved_domains set label=p_label,is_active=p_is_active,updated_by_id=p_actor_id,updated_at=clock_timestamp() where id=v_row_id; end if;
    select pg_catalog.to_jsonb(d.*) into v_after from public.m04_ads_approved_domains d where d.id=v_row_id;
  elsif p_kind='trusted_network' then
    select pg_catalog.to_jsonb(n.*),n.id into v_before,v_row_id from public.m04_ads_trusted_networks n where n.network=p_value::cidr for update;
    if v_row_id is null then insert into public.m04_ads_trusted_networks(network,label,is_active,created_by_id,updated_by_id) values(p_value::cidr,coalesce(nullif(p_label,''),p_value),p_is_active,p_actor_id,p_actor_id) returning id into v_row_id;
    else update public.m04_ads_trusted_networks set label=coalesce(nullif(p_label,''),label),is_active=p_is_active,updated_by_id=p_actor_id,updated_at=clock_timestamp() where id=v_row_id; end if;
    select pg_catalog.to_jsonb(n.*) into v_after from public.m04_ads_trusted_networks n where n.id=v_row_id;
  else raise exception 'unsupported_m04_setting_kind'; end if;
  insert into public.m04_ads_admin_events(action,setting_kind,setting_identity,before_value,after_value,actor_id,trusted_ip,trusted_user_agent,idempotency_key) values(case when v_before is null then 'created' when p_is_active then 'activated_or_updated' else 'deactivated' end,p_kind,p_value,v_before,v_after,p_actor_id,p_trusted_ip,left(p_trusted_user_agent,1000),p_idempotency_key);
  return v_after;
end;
$$;

do $$ declare t text; begin
  foreach t in array array['m03_ads_change_item_attempts','m03_ads_admin_events','m04_ads_admin_events'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on table public.%I from public,anon,authenticated',t);
    execute format('grant all on table public.%I to service_role',t);
  end loop;
end $$;

revoke all on function m03_ads_internal.resolve_admin(uuid) from public,anon,authenticated,service_role;
revoke all on function m03_ads_internal.resolve_operator(uuid,inet) from public,anon,authenticated,service_role;
revoke all on function public.m03_ads_create_mock_change_request(text,text,text,uuid,text,text,bigint,bigint,jsonb,uuid,text,text) from public,anon,authenticated,service_role;
revoke all on function public.m03_ads_validate_mock_change_request(uuid,uuid,text,text) from public,anon,authenticated,service_role;
revoke all on function public.m03_ads_approve_mock_change_request(uuid,uuid,text,text,text) from public,anon,authenticated,service_role;

do $$ declare f regprocedure; begin
  foreach f in array array[
    'public.m03_ads_assert_operator_v1(uuid,inet,text)'::regprocedure,
    'public.m03_ads_create_mock_change_request_v2(text,text,text,uuid,text,text,bigint,bigint,text,uuid,uuid,jsonb,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_edit_mock_change_request_v2(uuid,bigint,text,text,bigint,bigint,text,uuid,uuid,jsonb,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_validate_mock_change_request_v2(uuid,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_approve_mock_change_request_v2(uuid,text,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_cancel_mock_change_request_v2(uuid,text,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_set_workflow_setting_v1(text,text,text,uuid,boolean,uuid,inet,text,text)'::regprocedure,
    'public.m04_ads_set_workflow_setting_v1(text,text,text,uuid,boolean,uuid,inet,text,text)'::regprocedure
  ] loop execute format('revoke all on function %s from public,anon,authenticated',f); execute format('grant execute on function %s to service_role',f); end loop;
end $$;

grant usage,select on all sequences in schema public to service_role;
