-- M03 Meta provider operation persistence. Provider execution remains deployment-locked.
-- Strictly additive/isolated: this migration mutates public.m03_ads_* objects only.

create table public.m03_ads_provider_operation_resources (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.m03_ads_change_requests(id) on delete cascade,
  revision_id uuid not null references public.m03_ads_change_request_revisions(id) on delete cascade,
  item_id uuid not null references public.m03_ads_change_items(id) on delete cascade,
  resource_mapping_id bigint references public.m03_ads_provider_resource_mappings(id) on delete set null,
  platform text not null default 'meta' check (platform = 'meta'),
  resource_role text not null check (resource_role in (
    'previous_ad','replacement_creative','replacement_ad'
  )),
  provider_resource_identity text,
  lifecycle_state text not null default 'planned' check (lifecycle_state in (
    'planned','created','verified','activated','disabled','failed','compensation_required'
  )),
  creation_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(creation_evidence) = 'object'),
  readback_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(readback_evidence) = 'object'),
  normalized_error jsonb not null default '{}'::jsonb check (jsonb_typeof(normalized_error) = 'object'),
  idempotency_key text not null unique,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  unique (item_id, resource_role)
);

create index m03_ads_provider_operation_resources_request_idx
  on public.m03_ads_provider_operation_resources (request_id, updated_at desc);
create index m03_ads_provider_operation_resources_revision_idx
  on public.m03_ads_provider_operation_resources (revision_id, updated_at desc);
create index m03_ads_provider_operation_resources_state_idx
  on public.m03_ads_provider_operation_resources (lifecycle_state, updated_at desc);

alter table public.m03_ads_change_item_attempts
  drop constraint if exists m03_ads_change_item_attempts_result_check;
alter table public.m03_ads_change_item_attempts
  add constraint m03_ads_change_item_attempts_result_check check (result in (
    'provider_execution_locked','pending','succeeded','failed','verified','mismatch','compensation_required'
  ));

alter table public.m03_ads_provider_operation_resources enable row level security;
revoke all on table public.m03_ads_provider_operation_resources from public, anon, authenticated;
grant select, insert, update on table public.m03_ads_provider_operation_resources to service_role;
grant usage, select on sequence public.m03_ads_provider_operation_resources_id_seq to service_role;

create or replace function public.m03_ads_record_meta_operation_resource_v1(
  p_request_id uuid,
  p_revision_id uuid,
  p_item_id uuid,
  p_resource_mapping_id bigint,
  p_resource_role text,
  p_provider_resource_identity text,
  p_expected_lifecycle_state text,
  p_lifecycle_state text,
  p_creation_evidence jsonb,
  p_readback_evidence jsonb,
  p_normalized_error jsonb,
  p_actor_id uuid,
  p_trusted_ip inet,
  p_trusted_user_agent text,
  p_idempotency_key text
) returns public.m03_ads_provider_operation_resources
language plpgsql security definer set search_path = '' as $$
declare
  v_request public.m03_ads_change_requests;
  v_revision public.m03_ads_change_request_revisions;
  v_approval public.m03_ads_change_approvals;
  v_row public.m03_ads_provider_operation_resources;
  v_actor record;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id, p_trusted_ip);
  select * into v_row from public.m03_ads_provider_operation_resources where idempotency_key = p_idempotency_key;
  if found then
    if v_row.request_id <> p_request_id or v_row.revision_id <> p_revision_id
      or v_row.item_id <> p_item_id or v_row.resource_role <> p_resource_role then
      raise exception 'idempotency_key_reused_for_different_meta_resource';
    end if;
    return v_row;
  end if;
  if jsonb_typeof(coalesce(p_creation_evidence, '{}'::jsonb)) <> 'object'
    or jsonb_typeof(coalesce(p_readback_evidence, '{}'::jsonb)) <> 'object'
    or jsonb_typeof(coalesce(p_normalized_error, '{}'::jsonb)) <> 'object' then
    raise exception 'invalid_meta_operation_evidence';
  end if;

  select * into v_request from public.m03_ads_change_requests where id = p_request_id for update;
  if not found then raise exception 'change_request_not_found'; end if;
  if v_request.platform <> 'meta' then raise exception 'meta_request_required'; end if;
  select * into v_revision from public.m03_ads_change_request_revisions
    where id = p_revision_id and request_id = p_request_id;
  if not found then raise exception 'revision_not_owned_by_request'; end if;
  select * into v_approval from public.m03_ads_change_approvals
    where request_id = p_request_id and revision_id = p_revision_id
      and revision_hash = v_revision.payload_hash
    order by created_at desc limit 1;
  if not found then raise exception 'exact_revision_approval_required'; end if;
  if not exists (
    select 1 from public.m03_ads_change_items where id = p_item_id and request_id = p_request_id
  ) then raise exception 'change_item_not_owned_by_request'; end if;
  if p_resource_mapping_id is not null and not exists (
    select 1 from public.m03_ads_provider_resource_mappings
    where id = p_resource_mapping_id and request_id = p_request_id and item_id = p_item_id and platform = 'meta'
  ) then raise exception 'resource_mapping_not_owned_by_item'; end if;

  select * into v_row from public.m03_ads_provider_operation_resources
    where item_id = p_item_id and resource_role = p_resource_role for update;
  if found then
    if v_row.revision_id <> p_revision_id then raise exception 'operation_resource_revision_mismatch'; end if;
    if p_expected_lifecycle_state is not null and v_row.lifecycle_state <> p_expected_lifecycle_state then
      raise exception 'stale_provider_operation_stage';
    end if;
    if v_row.lifecycle_state <> p_lifecycle_state and not (
      (v_row.lifecycle_state = 'planned' and p_lifecycle_state in ('created','verified','disabled','failed'))
      or (v_row.lifecycle_state = 'created' and p_lifecycle_state in ('verified','failed'))
      or (v_row.lifecycle_state = 'verified' and p_lifecycle_state in ('activated','disabled','failed'))
      or (v_row.lifecycle_state = 'activated' and p_lifecycle_state in ('disabled','failed','compensation_required'))
      or (v_row.lifecycle_state = 'disabled' and p_lifecycle_state in ('verified','compensation_required'))
      or (v_row.lifecycle_state = 'failed' and p_lifecycle_state in ('planned','created'))
      or (v_row.lifecycle_state = 'compensation_required' and p_lifecycle_state in ('disabled','failed'))
    ) then raise exception 'invalid_meta_operation_stage_transition'; end if;
    update public.m03_ads_provider_operation_resources set
      provider_resource_identity = coalesce(nullif(pg_catalog.btrim(p_provider_resource_identity), ''), provider_resource_identity),
      lifecycle_state = p_lifecycle_state,
      creation_evidence = case when p_creation_evidence is null then creation_evidence else p_creation_evidence end,
      readback_evidence = case when p_readback_evidence is null then readback_evidence else p_readback_evidence end,
      normalized_error = case when p_normalized_error is null then normalized_error else p_normalized_error end,
      updated_at = clock_timestamp()
    where id = v_row.id returning * into v_row;
  else
    if p_expected_lifecycle_state is not null and p_expected_lifecycle_state <> 'planned' then
      raise exception 'stale_provider_operation_stage';
    end if;
    insert into public.m03_ads_provider_operation_resources(
      request_id, revision_id, item_id, resource_mapping_id, resource_role,
      provider_resource_identity, lifecycle_state, creation_evidence, readback_evidence,
      normalized_error, idempotency_key
    ) values (
      p_request_id, p_revision_id, p_item_id, p_resource_mapping_id, p_resource_role,
      nullif(pg_catalog.btrim(p_provider_resource_identity), ''), p_lifecycle_state,
      coalesce(p_creation_evidence, '{}'::jsonb), coalesce(p_readback_evidence, '{}'::jsonb),
      coalesce(p_normalized_error, '{}'::jsonb), p_idempotency_key
    ) returning * into v_row;
  end if;

  insert into public.m03_ads_change_events(
    request_id, revision_id, event_type, actor_id, actor_name, trusted_ip, trusted_user_agent, metadata
  ) values (
    p_request_id, p_revision_id, 'meta_provider_operation_resource_advanced', p_actor_id,
    v_actor.actor_name, p_trusted_ip, left(p_trusted_user_agent, 1000),
    jsonb_build_object('resource_id', v_row.id, 'item_id', p_item_id, 'role', p_resource_role,
      'lifecycle_state', p_lifecycle_state, 'provider_execution_locked', true)
  );
  return v_row;
end;
$$;

create or replace function public.m03_ads_record_meta_item_attempt_v1(
  p_request_id uuid,
  p_item_id uuid,
  p_revision_id uuid,
  p_action text,
  p_attempt_number integer,
  p_idempotency_key text,
  p_operation_key text,
  p_result text,
  p_replacement_stage text,
  p_provider_request jsonb,
  p_provider_result_evidence jsonb,
  p_readback_evidence jsonb,
  p_normalized_error jsonb,
  p_actor_id uuid,
  p_trusted_ip inet,
  p_trusted_user_agent text
) returns public.m03_ads_change_item_attempts
language plpgsql security definer set search_path = '' as $$
declare
  v_request public.m03_ads_change_requests;
  v_revision public.m03_ads_change_request_revisions;
  v_row public.m03_ads_change_item_attempts;
  v_actor record;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id, p_trusted_ip);
  select * into v_row from public.m03_ads_change_item_attempts where operation_key = p_operation_key;
  if found then
    if v_row.request_id <> p_request_id or v_row.revision_id <> p_revision_id or v_row.item_id <> p_item_id then
      raise exception 'operation_key_reused_for_different_meta_attempt';
    end if;
    return v_row;
  end if;
  if p_result not in ('provider_execution_locked','pending','succeeded','failed','verified','mismatch','compensation_required') then
    raise exception 'invalid_meta_attempt_result';
  end if;
  if jsonb_typeof(coalesce(p_provider_request, '{}'::jsonb)) <> 'object'
    or jsonb_typeof(coalesce(p_provider_result_evidence, '{}'::jsonb)) <> 'object'
    or jsonb_typeof(coalesce(p_readback_evidence, '{}'::jsonb)) <> 'object'
    or jsonb_typeof(coalesce(p_normalized_error, '{}'::jsonb)) <> 'object' then
    raise exception 'invalid_meta_attempt_evidence';
  end if;
  select * into v_request from public.m03_ads_change_requests where id = p_request_id for update;
  if not found or v_request.platform <> 'meta' then raise exception 'meta_change_request_not_found'; end if;
  select * into v_revision from public.m03_ads_change_request_revisions
    where id = p_revision_id and request_id = p_request_id;
  if not found then raise exception 'revision_not_owned_by_request'; end if;
  if not exists (
    select 1 from public.m03_ads_change_approvals
    where request_id = p_request_id and revision_id = p_revision_id and revision_hash = v_revision.payload_hash
  ) then raise exception 'exact_revision_approval_required'; end if;
  if not exists (
    select 1 from public.m03_ads_change_items where id = p_item_id and request_id = p_request_id
  ) then raise exception 'change_item_not_owned_by_request'; end if;

  insert into public.m03_ads_change_item_attempts(
    request_id, item_id, revision_id, action, attempt_number, idempotency_key, operation_key,
    result, replacement_stage, provider_request, provider_result_evidence, readback_evidence, normalized_error
  ) values (
    p_request_id, p_item_id, p_revision_id, p_action, p_attempt_number, p_idempotency_key, p_operation_key,
    p_result, p_replacement_stage, coalesce(p_provider_request, '{}'::jsonb),
    coalesce(p_provider_result_evidence, '{}'::jsonb), coalesce(p_readback_evidence, '{}'::jsonb),
    coalesce(p_normalized_error, '{}'::jsonb)
  ) returning * into v_row;
  insert into public.m03_ads_change_events(
    request_id, revision_id, event_type, actor_id, actor_name, trusted_ip, trusted_user_agent, metadata
  ) values (
    p_request_id, p_revision_id, 'meta_item_attempt_recorded', p_actor_id, v_actor.actor_name,
    p_trusted_ip, left(p_trusted_user_agent, 1000),
    jsonb_build_object('attempt_id', v_row.id, 'operation_key', p_operation_key, 'result', p_result)
  );
  return v_row;
end;
$$;

create or replace function public.m03_ads_record_meta_readback_v1(
  p_request_id uuid,
  p_revision_id uuid,
  p_item_id uuid,
  p_operation_key text,
  p_readback_evidence jsonb,
  p_matches_approved_value boolean,
  p_actor_id uuid,
  p_trusted_ip inet,
  p_trusted_user_agent text,
  p_idempotency_key text
) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_request public.m03_ads_change_requests;
  v_revision public.m03_ads_change_request_revisions;
  v_claim public.m03_ads_idempotency_claims;
  v_actor record;
  v_response jsonb;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id, p_trusted_ip);
  select * into v_claim from public.m03_ads_idempotency_claims
    where action = 'meta_readback_v1' and idempotency_key = p_idempotency_key;
  if found then
    if v_claim.request_id <> p_request_id or v_claim.response_snapshot->>'item_id' <> p_item_id::text then
      raise exception 'idempotency_key_reused_for_different_meta_readback';
    end if;
    return v_claim.response_snapshot;
  end if;
  if jsonb_typeof(coalesce(p_readback_evidence, '{}'::jsonb)) <> 'object' then
    raise exception 'invalid_meta_readback_evidence';
  end if;
  select * into v_request from public.m03_ads_change_requests where id = p_request_id for update;
  if not found or v_request.platform <> 'meta' then raise exception 'meta_change_request_not_found'; end if;
  select * into v_revision from public.m03_ads_change_request_revisions
    where id = p_revision_id and request_id = p_request_id;
  if not found then raise exception 'revision_not_owned_by_request'; end if;
  if not exists (
    select 1 from public.m03_ads_change_approvals
    where request_id = p_request_id and revision_id = p_revision_id and revision_hash = v_revision.payload_hash
  ) then raise exception 'exact_revision_approval_required'; end if;
  update public.m03_ads_change_items set
    readback_evidence = coalesce(p_readback_evidence, '{}'::jsonb),
    provider_result_evidence = provider_result_evidence || jsonb_build_object(
      'operation_key', p_operation_key,
      'verification_result', case when p_matches_approved_value then 'verified' else 'mismatch' end
    )
  where id = p_item_id and request_id = p_request_id;
  if not found then raise exception 'change_item_not_owned_by_request'; end if;
  v_response := jsonb_build_object(
    'request_id', p_request_id, 'revision_id', p_revision_id, 'item_id', p_item_id,
    'operation_key', p_operation_key,
    'result', case when p_matches_approved_value then 'verified' else 'mismatch' end
  );
  insert into public.m03_ads_change_events(
    request_id, revision_id, event_type, actor_id, actor_name, trusted_ip, trusted_user_agent, metadata
  ) values (
    p_request_id, p_revision_id,
    case when p_matches_approved_value then 'meta_readback_verified' else 'meta_readback_mismatch' end,
    p_actor_id, v_actor.actor_name, p_trusted_ip, left(p_trusted_user_agent, 1000), v_response
  );
  insert into public.m03_ads_idempotency_claims(action, request_id, idempotency_key, response_snapshot)
  values ('meta_readback_v1', p_request_id, p_idempotency_key, v_response);
  return v_response;
end;
$$;

create or replace function public.m03_ads_derive_request_status_v1(
  p_request_id uuid,
  p_revision_id uuid,
  p_actor_id uuid,
  p_trusted_ip inet,
  p_trusted_user_agent text,
  p_idempotency_key text
) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_request public.m03_ads_change_requests;
  v_revision public.m03_ads_change_request_revisions;
  v_claim public.m03_ads_idempotency_claims;
  v_actor record;
  v_total integer;
  v_verified integer;
  v_failed integer;
  v_succeeded integer;
  v_status text;
  v_response jsonb;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id, p_trusted_ip);
  select * into v_claim from public.m03_ads_idempotency_claims
    where action = 'derive_request_status_v1' and idempotency_key = p_idempotency_key;
  if found then
    if v_claim.request_id <> p_request_id then raise exception 'idempotency_key_reused_for_different_request'; end if;
    return v_claim.response_snapshot;
  end if;
  select * into v_request from public.m03_ads_change_requests where id = p_request_id for update;
  if not found or v_request.platform <> 'meta' then raise exception 'meta_change_request_not_found'; end if;
  select * into v_revision from public.m03_ads_change_request_revisions
    where id = p_revision_id and request_id = p_request_id;
  if not found then raise exception 'revision_not_owned_by_request'; end if;
  if not exists (
    select 1 from public.m03_ads_change_approvals
    where request_id = p_request_id and revision_id = p_revision_id and revision_hash = v_revision.payload_hash
  ) then raise exception 'exact_revision_approval_required'; end if;
  select count(*) into v_total from public.m03_ads_change_items where request_id = p_request_id;
  select
    count(*) filter (where latest.result = 'verified'),
    count(*) filter (where latest.result in ('failed','mismatch','compensation_required')),
    count(*) filter (where latest.result = 'succeeded')
  into v_verified, v_failed, v_succeeded
  from (
    select distinct on (item_id) item_id, result
    from public.m03_ads_change_item_attempts
    where request_id = p_request_id and revision_id = p_revision_id
    order by item_id, created_at desc, id desc
  ) latest;
  v_status := case
    when v_total > 0 and v_verified = v_total then 'verified'
    when v_failed > 0 and (v_verified > 0 or v_succeeded > 0) then 'partially_completed'
    when v_failed > 0 then 'failed'
    when v_succeeded > 0 then 'published'
    else v_request.status
  end;
  update public.m03_ads_change_requests set
    status = v_status, updated_at = clock_timestamp(), lock_version = lock_version + 1
  where id = p_request_id returning * into v_request;
  v_response := jsonb_build_object(
    'request_id', p_request_id, 'revision_id', p_revision_id, 'status', v_status,
    'verified_items', v_verified, 'failed_items', v_failed, 'succeeded_items', v_succeeded,
    'total_items', v_total, 'lock_version', v_request.lock_version
  );
  insert into public.m03_ads_change_events(
    request_id, revision_id, event_type, actor_id, actor_name, trusted_ip, trusted_user_agent, metadata
  ) values (
    p_request_id, p_revision_id, 'meta_request_status_derived', p_actor_id, v_actor.actor_name,
    p_trusted_ip, left(p_trusted_user_agent, 1000), v_response
  );
  insert into public.m03_ads_idempotency_claims(action, request_id, idempotency_key, response_snapshot)
  values ('derive_request_status_v1', p_request_id, p_idempotency_key, v_response);
  return v_response;
end;
$$;

create or replace function public.m03_ads_finalize_meta_item_v1(
  p_request_id uuid,
  p_revision_id uuid,
  p_item_id uuid,
  p_result text,
  p_provider_result_evidence jsonb,
  p_readback_evidence jsonb,
  p_normalized_error jsonb,
  p_actor_id uuid,
  p_trusted_ip inet,
  p_trusted_user_agent text,
  p_idempotency_key text
) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_request public.m03_ads_change_requests;
  v_revision public.m03_ads_change_request_revisions;
  v_claim public.m03_ads_idempotency_claims;
  v_actor record;
  v_response jsonb;
begin
  select * into v_actor from m03_ads_internal.resolve_operator(p_actor_id, p_trusted_ip);
  select * into v_claim from public.m03_ads_idempotency_claims
    where action = 'finalize_meta_item_v1' and idempotency_key = p_idempotency_key;
  if found then
    if v_claim.request_id <> p_request_id or v_claim.response_snapshot->>'item_id' <> p_item_id::text then
      raise exception 'idempotency_key_reused_for_different_meta_item';
    end if;
    return v_claim.response_snapshot;
  end if;
  if p_result not in ('provider_execution_locked','pending','succeeded','failed','verified','mismatch','compensation_required') then
    raise exception 'invalid_meta_item_result';
  end if;
  if jsonb_typeof(coalesce(p_provider_result_evidence, '{}'::jsonb)) <> 'object'
    or jsonb_typeof(coalesce(p_readback_evidence, '{}'::jsonb)) <> 'object'
    or jsonb_typeof(coalesce(p_normalized_error, '{}'::jsonb)) <> 'object' then
    raise exception 'invalid_meta_item_evidence';
  end if;
  select * into v_request from public.m03_ads_change_requests where id = p_request_id for update;
  if not found or v_request.platform <> 'meta' then raise exception 'meta_change_request_not_found'; end if;
  select * into v_revision from public.m03_ads_change_request_revisions
    where id = p_revision_id and request_id = p_request_id;
  if not found then raise exception 'revision_not_owned_by_request'; end if;
  if not exists (
    select 1 from public.m03_ads_change_approvals
    where request_id = p_request_id and revision_id = p_revision_id and revision_hash = v_revision.payload_hash
  ) then raise exception 'exact_revision_approval_required'; end if;
  update public.m03_ads_change_items set
    provider_result_evidence = coalesce(p_provider_result_evidence, '{}'::jsonb),
    readback_evidence = coalesce(p_readback_evidence, '{}'::jsonb),
    validation_issues = case
      when p_result in ('failed','mismatch','compensation_required') then
        jsonb_build_array(jsonb_build_object(
          'path', field_path,
          'message', coalesce(nullif(p_normalized_error->>'message', ''), 'Meta operation requires attention.'),
          'severity', 'error'
        ))
      else '[]'::jsonb
    end
  where id = p_item_id and request_id = p_request_id;
  if not found then raise exception 'change_item_not_owned_by_request'; end if;
  v_response := jsonb_build_object(
    'request_id', p_request_id, 'revision_id', p_revision_id, 'item_id', p_item_id, 'result', p_result
  );
  insert into public.m03_ads_change_events(
    request_id, revision_id, event_type, actor_id, actor_name, trusted_ip, trusted_user_agent, metadata
  ) values (
    p_request_id, p_revision_id, 'meta_item_finalized', p_actor_id, v_actor.actor_name,
    p_trusted_ip, left(p_trusted_user_agent, 1000),
    v_response || jsonb_build_object('normalized_error', coalesce(p_normalized_error, '{}'::jsonb))
  );
  insert into public.m03_ads_idempotency_claims(action, request_id, idempotency_key, response_snapshot)
  values ('finalize_meta_item_v1', p_request_id, p_idempotency_key, v_response);
  return v_response;
end;
$$;

do $$ declare f regprocedure; begin
  foreach f in array array[
    'public.m03_ads_record_meta_operation_resource_v1(uuid,uuid,uuid,bigint,text,text,text,text,jsonb,jsonb,jsonb,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_record_meta_item_attempt_v1(uuid,uuid,uuid,text,integer,text,text,text,text,jsonb,jsonb,jsonb,jsonb,uuid,inet,text)'::regprocedure,
    'public.m03_ads_record_meta_readback_v1(uuid,uuid,uuid,text,jsonb,boolean,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_derive_request_status_v1(uuid,uuid,uuid,inet,text,text)'::regprocedure,
    'public.m03_ads_finalize_meta_item_v1(uuid,uuid,uuid,text,jsonb,jsonb,jsonb,uuid,inet,text,text)'::regprocedure
  ] loop
    execute format('revoke all on function %s from public,anon,authenticated', f);
    execute format('grant execute on function %s to service_role', f);
  end loop;
end $$;

comment on table public.m03_ads_provider_operation_resources is
  'M03 Meta creative-replacement operation resources and durable saga stages. Provider execution remains deployment-locked.';
