alter table public.ad_automation_search_term_analysis_batches
  add column if not exists input_r2_key text,
  add column if not exists input_checksum text,
  add column if not exists input_expires_at timestamptz,
  add column if not exists saved_row_count smallint not null default 0,
  add column if not exists last_worker_ping_at timestamptz;

create table if not exists public.ad_automation_search_term_analysis_rows (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.ad_automation_search_term_analysis_jobs(id) on delete cascade,
  batch_id uuid not null references public.ad_automation_search_term_analysis_batches(id) on delete cascade,
  batch_number smallint not null check (batch_number between 1 and 10),
  stable_term_key text not null,
  search_term text not null,
  campaign_id text,
  campaign_name text not null default '',
  ad_group_id text,
  ad_group_name text not null default '',
  destination_url text not null default '',
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  spend numeric not null default 0,
  conversions numeric not null default 0,
  classification text not null default '',
  proposed_action text not null default '',
  safety_score numeric not null default 0,
  safety_band text,
  execution_status text,
  verification_status text,
  review_status text,
  review_decision text,
  result_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (job_id, stable_term_key)
);

create index if not exists ad_automation_search_term_rows_job_batch_idx
  on public.ad_automation_search_term_analysis_rows (job_id, batch_number, id);
create index if not exists ad_automation_search_term_rows_filter_idx
  on public.ad_automation_search_term_analysis_rows (job_id, proposed_action, classification);

alter table public.ad_automation_search_term_analysis_rows enable row level security;
grant select, insert, update, delete on public.ad_automation_search_term_analysis_rows to service_role;
grant usage, select on sequence public.ad_automation_search_term_analysis_rows_id_seq to service_role;

create or replace function public.commit_search_term_analysis_batch(
  requested_job_id uuid,
  requested_batch_id uuid,
  expected_row_count integer,
  reviewed_rows jsonb,
  requested_checksum text default null
) returns table(saved_row_count integer, completed_runs integer, total_saved_rows integer)
language plpgsql
security invoker
set search_path = public
as $$
declare
  selected_batch public.ad_automation_search_term_analysis_batches;
  payload_count integer;
  persisted_count integer;
begin
  select * into selected_batch
  from public.ad_automation_search_term_analysis_batches
  where id = requested_batch_id and job_id = requested_job_id
  for update;
  if not found then raise exception 'SEARCH_TERM_BATCH_NOT_FOUND'; end if;
  if jsonb_typeof(reviewed_rows) <> 'array' then raise exception 'SEARCH_TERM_BATCH_ROWS_INVALID'; end if;
  select jsonb_array_length(reviewed_rows) into payload_count;
  if payload_count <> expected_row_count or expected_row_count <> selected_batch.term_count then
    raise exception 'SEARCH_TERM_BATCH_COUNT_MISMATCH expected %, payload %, batch %', expected_row_count, payload_count, selected_batch.term_count;
  end if;

  insert into public.ad_automation_search_term_analysis_rows (
    job_id,batch_id,batch_number,stable_term_key,search_term,campaign_id,campaign_name,
    ad_group_id,ad_group_name,destination_url,impressions,clicks,spend,conversions,
    classification,proposed_action,safety_score,safety_band,execution_status,
    verification_status,review_status,review_decision,result_json,updated_at
  )
  select requested_job_id,requested_batch_id,selected_batch.run_number,
    item->>'stableTermKey',coalesce(item->>'searchTerm',''),nullif(item->>'campaignId',''),
    coalesce(item->>'campaign',item->>'campaignName',''),nullif(item->>'adGroupId',''),
    coalesce(item->>'adGroup',item->>'adGroupName',''),coalesce(item->>'destinationUrl',''),
    coalesce((item->>'impressions')::bigint,0),coalesce((item->>'clicks')::bigint,0),
    coalesce((item->>'spend')::numeric,0),coalesce((item->>'conversions')::numeric,0),
    coalesce(item->>'classification',''),coalesce(item->>'proposedAction',''),
    coalesce((item->>'safetyScore')::numeric,0),item->>'safetyBand',item->>'executionStatus',
    item->>'verificationStatus',item->>'reviewStatus',item->>'reviewDecision',item,now()
  from jsonb_array_elements(reviewed_rows) item
  where coalesce(item->>'stableTermKey','') <> ''
  on conflict (job_id,stable_term_key) do update set
    batch_id=excluded.batch_id,batch_number=excluded.batch_number,result_json=excluded.result_json,
    classification=excluded.classification,proposed_action=excluded.proposed_action,
    safety_score=excluded.safety_score,safety_band=excluded.safety_band,
    execution_status=excluded.execution_status,verification_status=excluded.verification_status,
    updated_at=now();

  select count(*) into persisted_count
  from public.ad_automation_search_term_analysis_rows where batch_id=requested_batch_id;
  if persisted_count <> expected_row_count then
    raise exception 'SEARCH_TERM_BATCH_SAVE_VERIFICATION_FAILED expected %, saved %', expected_row_count, persisted_count;
  end if;

  update public.ad_automation_search_term_analysis_batches set
    status='completed',saved_row_count=persisted_count,input_checksum=coalesce(requested_checksum,input_checksum),
    completed_at=coalesce(completed_at,now()),error=null,updated_at=now()
  where id=requested_batch_id;

  update public.ad_automation_search_term_analysis_jobs job set
    completed_runs=(select count(*) from public.ad_automation_search_term_analysis_batches b where b.job_id=job.id and b.status='completed'),
    terms_processed=(select count(*) from public.ad_automation_search_term_analysis_rows row where row.job_id=job.id),
    last_worker_ping_at=now(),updated_at=now()
  where job.id=requested_job_id;

  return query select persisted_count,
    (select count(*)::integer from public.ad_automation_search_term_analysis_batches b where b.job_id=requested_job_id and b.status='completed'),
    (select count(*)::integer from public.ad_automation_search_term_analysis_rows row where row.job_id=requested_job_id);
end;
$$;

revoke all on function public.commit_search_term_analysis_batch(uuid,uuid,integer,jsonb,text) from public,anon,authenticated;
grant execute on function public.commit_search_term_analysis_batch(uuid,uuid,integer,jsonb,text) to service_role;
