begin;

create table if not exists public.ad_automation_placement_jobs (
  id uuid primary key,
  google_customer_id text not null,
  customer_name text,
  reporting_start_date date not null,
  reporting_end_date date not null,
  status text not null check (status in ('queued','running','partial','completed','failed','cancelled')),
  stage text not null,
  processed_rows integer not null default 0,
  total_rows integer,
  error text,
  cancellation_requested boolean not null default false,
  r2_object_key text,
  next_offset integer not null default 0,
  imported_rows integer not null default 0,
  import_all_requested boolean not null default false,
  source_expires_at timestamptz,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.ad_automation_placement_runs_v2 (
  id bigint generated by default as identity primary key,
  job_id uuid references public.ad_automation_placement_jobs(id) on delete set null,
  google_customer_id text not null,
  customer_name text not null,
  reporting_start_date date not null,
  reporting_end_date date not null,
  analyzed_at timestamptz not null,
  campaign_types jsonb not null default '[]'::jsonb,
  placement_count integer not null default 0,
  total_impressions bigint not null default 0,
  total_spend numeric not null default 0,
  unique_sites integer not null default 0,
  top_sites jsonb not null default '[]'::jsonb,
  imported_count integer not null default 0,
  total_available integer not null default 0,
  is_complete boolean not null default false,
  created_at timestamptz not null default now(),
  unique (google_customer_id, reporting_start_date, reporting_end_date)
);

create table if not exists public.ad_automation_placement_rows_v2 (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.ad_automation_placement_runs_v2(id) on delete cascade,
  source_view text not null,
  stable_key text not null,
  resource_name text not null,
  placement text not null,
  display_name text not null,
  placement_type text not null,
  target_url text,
  campaign_id text,
  campaign_name text not null,
  campaign_type text not null,
  ad_group_id text,
  ad_group_name text not null,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  spend numeric not null default 0,
  conversions numeric not null default 0,
  video_views bigint not null default 0,
  classification text not null default 'Awaiting review',
  recommended_action text not null default 'keep',
  confidence numeric not null default 0,
  reason text not null default 'Internal placement history only. No Google Ads change has been applied.',
  confirmation_required boolean not null default false,
  ai_status text not null default 'not_required',
  review_status text not null default 'pending_optimizer',
  current_decision text,
  reviewed_at timestamptz,
  reviewer_email text,
  reviewer_role text,
  unique (run_id, stable_key)
);

create index if not exists ad_placement_jobs_account_idx
  on public.ad_automation_placement_jobs (google_customer_id, started_at desc);
create index if not exists ad_placement_jobs_status_idx
  on public.ad_automation_placement_jobs (status, updated_at desc);
create index if not exists ad_placement_runs_v2_account_idx
  on public.ad_automation_placement_runs_v2 (google_customer_id, reporting_start_date, reporting_end_date);
create index if not exists ad_placement_rows_v2_run_impressions_idx
  on public.ad_automation_placement_rows_v2 (run_id, impressions desc, id);
create index if not exists ad_placement_rows_v2_filters_idx
  on public.ad_automation_placement_rows_v2 (run_id, campaign_type, placement_type, review_status);

alter table public.ad_automation_placement_jobs enable row level security;
alter table public.ad_automation_placement_runs_v2 enable row level security;
alter table public.ad_automation_placement_rows_v2 enable row level security;
revoke all on public.ad_automation_placement_jobs, public.ad_automation_placement_runs_v2, public.ad_automation_placement_rows_v2 from anon, authenticated;

commit;
